import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

const shellIndexPath = path.resolve(process.cwd(), 'companion-desktop/shell/index.html');
const rootIndexPath = path.resolve(process.cwd(), 'index.html');
const shellMainPath = path.resolve(process.cwd(), 'companion-desktop/main.cjs');
const shellPreloadPath = path.resolve(process.cwd(), 'companion-desktop/preload-shell.cjs');
const copilotPanelPath = path.resolve(process.cwd(), 'companion-desktop/shell/copilot-panel.js');
const authApiPath = path.resolve(process.cwd(), 'server/auth-api.js');
const scriptHubClientPath = path.resolve(process.cwd(), 'companion-desktop/agent-script-hub-client.cjs');
const packageJsonPath = path.resolve(process.cwd(), 'package.json');
const codexOneClickCheckPath = path.resolve(process.cwd(), 'scripts/check-codex-one-click-readiness.mjs');
const codexAuthEnvExportPath = path.resolve(process.cwd(), 'scripts/export-codex-shared-auth-env.mjs');
const codexAuthEnvCheckPath = path.resolve(process.cwd(), 'scripts/validate-codex-shared-auth-env.mjs');
const codexProductionCheckPath = path.resolve(process.cwd(), 'scripts/verify-codex-one-click-production.mjs');
const codexCleanMachineCheckPath = path.resolve(process.cwd(), 'scripts/verify-codex-clean-machine.mjs');
const codexCleanMachinePs1Path = path.resolve(process.cwd(), 'scripts/verify-codex-clean-machine.ps1');
const desktopUploadManifestPath = path.resolve(process.cwd(), 'scripts/prepare-companion-desktop-upload-manifest.mjs');
const desktopPublishPath = path.resolve(process.cwd(), 'scripts/publish-companion-desktop-artifact.mjs');
const codexFinalizeProductionPath = path.resolve(process.cwd(), 'scripts/finalize-codex-one-click-production.mjs');
const companionReleaseCheckPath = path.resolve(process.cwd(), 'scripts/companion-desktop-release-check.ps1');
const renderYamlPath = path.resolve(process.cwd(), 'render.yaml');

describe('copilot settings UI', () => {
  it('removes the legacy Copilot / Codex settings surface; butler is dsh', () => {
    const html = fs.readFileSync(shellIndexPath, 'utf8');
    expect(html).not.toContain('inpLegacyCopilotDebug');
    expect(html).not.toContain('调试旧 Copilot');
    expect(html).not.toContain("window.__loadLegacyCopilot");
    expect(html).not.toContain('id="shell-copilot"');
    expect(html).not.toContain('id="copilot-toggle"');
    expect(html).not.toContain('id="settings-agent"');
    expect(html).not.toContain('inpCodexCommand');
    expect(html).not.toContain('Workflow Tool Bridge');
    expect(html).not.toContain('id="pluginRows"');
    expect(html).not.toMatch(/<script src="copilot-panel\.js"><\/script>/);
    expect(html).toContain('id="btnDshPaneToggle"');
  });

  it('keeps the shell page scripts parseable after wiring product entrances', () => {
    const html = fs.readFileSync(shellIndexPath, 'utf8');
    const scripts = [...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map((m) => m[1]);
    expect(scripts.length).toBeGreaterThan(0);

    for (const script of scripts) {
      expect(() => new Function(script)).not.toThrow();
    }
    expect(() => new Function(fs.readFileSync(copilotPanelPath, 'utf8'))).not.toThrow();
  });

  it('keeps visible shell and Copilot UI text free of mojibake markers', () => {
    const checkedFiles = [shellIndexPath, copilotPanelPath];
    const mojibakePatterns = [
      /[\uFFFD]/,
      /(?:\?){4,}/,
      /[\u93bc\u93bb\u95c1\u6d93\u9420\u95ca\u93b4\u7480]/,
      /[\u5a34\u6fee\u6fec\u6fe1\u9428\u95b3]/,
      /[\u9396\u934f\u93c8\u9422\u6957\u6faa]/,
      /閹锋帞绮\?/,
    ];

    for (const filePath of checkedFiles) {
      const text = fs.readFileSync(filePath, 'utf8');
      const matches = mojibakePatterns.flatMap((pattern) => {
        const match = text.match(pattern);
        return match ? [`${pattern}@${match.index ?? 0}`] : [];
      }).slice(0, 8);
      expect(matches, `${path.relative(process.cwd(), filePath)} mojibake markers`).toEqual([]);
    }
  });

  it('denoise casual Copilot chat: Chinese confirm, no composer task-thread, no tool-call bubbles', () => {
    const panel = fs.readFileSync(copilotPanelPath, 'utf8').replace(/\r\n/g, '\n');

    expect(panel).toContain("rejectBtn.textContent = '\\u62d2\\u7edd'");
    expect(panel).toContain("approveBtn.textContent = '\\u5141\\u8bb8'");
    expect(panel).not.toContain('閹锋帞绮?');
    expect(panel).not.toContain("appendTaskThreadCard(text, { source: 'composer' })");
    expect(panel).toContain("appendTaskThreadCard(text, { source: 'quick_task' })");
    expect(panel).toContain('const phrases = EXAMPLE_PHRASES.slice()');
    expect(panel).not.toContain("appendBubble('tool', '> '");
    expect(panel).not.toContain("appendBubble('tool', 'done '");
    expect(panel).toContain('shouldMuteActivityInChat');
    expect(panel).toContain('noteActivityProgress');
    expect(panel).toContain('formatCopilotAssistantText');
    expect(panel).toContain('function renderCopilotMarkdown');
    expect(panel).toContain('function appendCodeBlockMarkdown');
    expect(panel).toContain('function appendInlineMarkdown');
    expect(panel).toContain('copilot-code-copy');
    expect(panel).toContain('copilot-inline-code');
    expect(panel).toContain("el.classList.toggle('copilot-markdown', role === 'assistant')");
    expect(panel).toContain("renderCopilotMarkdown(el, raw)");
    expect(panel).toContain('if (activeTaskThreadEls)');
    expect(panel).toContain('function dismissPendingConfirmCards');
    expect(panel).toContain('if (card.parentNode) card.parentNode.removeChild(card)');
    expect(panel).not.toContain("status.textContent = 'Handled'");
  });

  it('exposes Copilot clear-history entrance through panel, preload, and main IPC', () => {
    const panel = fs.readFileSync(copilotPanelPath, 'utf8').replace(/\r\n/g, '\n');
    const html = fs.readFileSync(shellIndexPath, 'utf8').replace(/\r\n/g, '\n');
    const preload = fs.readFileSync(shellPreloadPath, 'utf8').replace(/\r\n/g, '\n');
    const main = fs.readFileSync(shellMainPath, 'utf8').replace(/\r\n/g, '\n');

    expect(html).not.toContain('id="copilot-clear-history"');
    expect(panel).toContain('clearCopilotHistory');
    expect(panel).toContain('agent.clearHistory');
    expect(preload).toContain("clearHistory: (sessionId) => timedInvoke('agent-session-clear-history'");
    expect(main).toContain("ipcMain.handle('agent-session-clear-history'");
    expect(main).toContain('agentSessionService.clearHistory');
  });

  it('supports object-scoped Copilot sessions for tools and hosts', () => {
    const panel = fs.readFileSync(copilotPanelPath, 'utf8').replace(/\r\n/g, '\n');
    const preload = fs.readFileSync(shellPreloadPath, 'utf8').replace(/\r\n/g, '\n');
    const main = fs.readFileSync(shellMainPath, 'utf8').replace(/\r\n/g, '\n');
    const toolsPage = fs.readFileSync(path.resolve(process.cwd(), 'companion-desktop/shell/tools-page.js'), 'utf8');
    const bridges = fs.readFileSync(path.resolve(process.cwd(), 'companion-desktop/shell/tools-bridges.js'), 'utf8');

    expect(panel).toContain('let activeObjectSessionId');
    expect(panel).toContain('function buildObjectSessionId');
    expect(panel).toContain('const explicitSessionId =');
    expect(panel).toContain('window.__acOpenCopilotObjectSession = openObjectSession');
    expect(panel).toContain('let activeObjectContextPrompt');
    expect(panel).toContain('function buildObjectContextPrompt');
    expect(panel).toContain('shell.onOpenCopilotObjectSession');
    expect(panel).toContain('agent.listMessages(currentSessionId())');
    expect(panel).toContain('agent.clearHistory(currentSessionId())');
    expect(panel).toContain("activeObjectContextPrompt + '\\n\\n\\u7528\\u6237\\u8fd9\\u6b21\\u8bf4\\uff1a\\n' + text");
    expect(panel).toContain('agent.send(outboundText, currentSessionId())');
    expect(preload).toContain("send: (text, sessionId) => timedInvoke('agent-session-send', { text, sessionId }");
    expect(preload).toContain('onOpenCopilotObjectSession');
    expect(main).toContain('agentSessionService.sendUserMessage(text, { sessionId })');
    expect(main).toContain("shell-open-copilot-object-session");
    expect(main).toContain("type: 'capability'");
    expect(main).toContain('fetchShellToolCapabilityContextForAutoFix(toolId)');
    expect(main).toContain('sessionId: capabilitySessionId');
    expect(main).toContain('sendUserMessage(outboundPrompt, { sessionId: capabilitySessionId })');
    expect(main).not.toContain("sendUserMessage(prompt, { sessionId: `tool-${toolId}` })");
    expect(toolsPage).not.toContain('__acOpenCopilotObjectSession');
    expect(toolsPage).toContain('openDshHandoff');
    expect(toolsPage).toContain("domain: 'tools'");
    expect(toolsPage).toContain('fetchToolCapabilityContext(shell, entry, toolId)');
    expect(toolsPage).toContain("'/v1/capability-packages/' + encodeURIComponent(capabilityId) + '/context'");
    expect(toolsPage).toContain('fallbackToolCapabilityContext');
    expect(toolsPage).toContain('\\u672c\\u5730\\u7248\\u672c');
    expect(toolsPage).toContain('\\u4e91\\u7aef\\u5386\\u53f2\\u7248\\u672c');
    expect(bridges).toContain('data-bridge-host-chat');
    expect(bridges).toContain("type: 'host'");
    expect(bridges).toContain('bridgeCopilotContext');
    expect(bridges).toContain('contextPrompt: this.bridgeCopilotContext(hostId)');
    expect(bridges).toContain('\\u63a2\\u6d4b\\u72b6\\u6001');
    expect(bridges).toContain('\\u9a8c\\u6536\\u8bc1\\u636e');
  });

  it('keeps assistant bubbles pre-wrap and mutes routine Codex activity cards', () => {
    const panel = fs.readFileSync(copilotPanelPath, 'utf8').replace(/\r\n/g, '\n');
    const html = fs.readFileSync(shellIndexPath, 'utf8').replace(/\r\n/g, '\n');

    expect(panel).toContain("return ev.phase === 'start' || ev.phase === 'done'");
    expect(panel).toContain('if (!shouldMuteActivityInChat(ev))');
    expect(panel).toContain("setBubbleText(bubble, 'assistant', streamingText)");
    expect(html).toContain('#shell-copilot .copilot-msg');
    expect(html).toMatch(/#shell-copilot \.copilot-msg \{[\s\S]*?white-space:\s*pre-wrap\s*!important/);
  });

  it('broadcasts capability creation results so pages can refresh after Copilot creates objects', () => {
    const panel = fs.readFileSync(copilotPanelPath, 'utf8').replace(/\r\n/g, '\n');

    expect(panel).toContain('function capabilityCreatedFromToolResult');
    expect(panel).toContain("name !== 'ac.capability.create_draft' && name !== 'ac.capability.draft_create'");
    expect(panel).toContain("ev.type === 'tool_result'");
    expect(panel).toContain("new CustomEvent('assetcutter:capability-created'");
    expect(panel).toContain("type !== 'software_connection' && type !== 'tool'");
  });

  it('uses Workbench as the first shell entry and moves home diagnostics into categorized settings', () => {
    const html = fs.readFileSync(shellIndexPath, 'utf8').replace(/\r\n/g, '\n');
    const main = fs.readFileSync(shellMainPath, 'utf8').replace(/\r\n/g, '\n');

    expect(html).not.toContain('id="view-home"');
    expect(html).not.toContain('data-view="home"');
    expect(html).toContain('data-view="workbench" class="active"');
    expect(html).not.toContain('aside class="shell-copilot"');
    expect(html).toContain('class="settings-section-nav"');
    expect(html).toContain('data-settings-section="overview"');
    expect(html).not.toContain('data-settings-section="entrances"');
    expect(html).not.toContain('data-settings-section="account"');
    expect(html).not.toContain('data-settings-section="agent"');
    expect(html).toContain('data-settings-section="storage"');
    expect(html).not.toContain('data-settings-section="service"');
    expect(html).toContain('data-settings-section-panel="overview"');
    expect(html).not.toContain('data-settings-section-panel="agent"');
    expect(html).toContain('function showSettingsSection');
    expect(html).toContain("showSettingsSection(activeSettingsSection, { preserveScroll: true })");
    expect(html).toContain("showSettingsSection(link.getAttribute('data-settings-section'))");
    expect(html).toContain('class="settings-group settings-overview is-active"');
    expect(html).toContain('.settings-content {\n      min-height: 0;\n      padding: 16px 18px 22px;\n      overflow: auto;\n      display: flex;');
    expect(html).toContain('max-width: 820px;');
    expect(html).toContain('.settings-group.is-active {\n      display: flex;\n      flex-direction: column;');
    expect(html).not.toContain('grid-template-columns: repeat(2, minmax(280px, 1fr));');
    expect(html).not.toContain('grid-template-columns: repeat(3, minmax(0, 1fr));');
    expect(html).toContain('id="settings-overview"');
    expect(html).not.toContain('id="settings-entrances"');
    expect(html).not.toContain('id="settings-account"');
    expect(html).not.toContain('id="settings-agent"');
    expect(html).toContain('id="settings-storage"');
    expect(html).not.toContain('id="settings-service"');
    expect(html).toContain('id="inpDownloadDir"');
    expect(html).toContain('id="inpWorkshopWorkspaceDir"');
    expect(html).not.toContain('id="inpVolumeRoot"');
    expect(html).not.toContain('id="inpSiteUrl"');
    expect(html).not.toContain('id="localBase"');
    expect(html).toContain('id="statusLabel"');
    expect(html).not.toContain('id="pluginRows"');
    expect(html).toContain("await applyShellView('workbench')");
    expect(html).not.toContain('views.home');

    expect(main).toContain("let shellMainProcessActiveView = 'workbench'");
    expect(main).not.toContain("shellMainProcessActiveView = 'home'");
    expect(main).not.toContain("view === 'home'");
  });

  it('does not expose Codex or Copilot controls on the settings page', () => {
    const html = fs.readFileSync(shellIndexPath, 'utf8');

    expect(html).not.toContain('id="inpCodexCommand"');
    expect(html).not.toContain('id="inpCodexCwd"');
    expect(html).not.toContain('id="inpCodexModel"');
    expect(html).not.toContain('id="codexSandboxPicker"');
    expect(html).not.toContain('id="codexRuntimeStatusDetail"');
    expect(html).not.toContain('id="btnSetupCodexRuntime"');
    expect(html).not.toContain('id="btnProbeCodexRuntime"');
    expect(html).not.toContain('id="btnCopyCodexSetupReport"');
    expect(html).not.toContain('id="agentMcpProbeCard"');
    expect(html).not.toContain('id="agentWorkflowPromotionCard"');
    expect(html).not.toContain('Copilot currently uses Codex only');
    expect(html).not.toContain('btnHermesOneClickSetup');
    expect(html).not.toContain('id="inpSiteUrl"');
    expect(html).not.toContain('id="btnOpenWorkbenchLogin"');
    expect(html).not.toContain('id="inpVolumeRoot"');
    expect(html).not.toContain('id="localBase"');
    expect(html).not.toContain('id="inpPairToken"');
  });

  it('keeps leftover Codex runtime helpers out of the settings page script', () => {
    const html = fs.readFileSync(shellIndexPath, 'utf8');

    expect(html).not.toContain('renderCodexRuntimeStatus');
    expect(html).not.toContain('codexRuntimeStatusCache');
    expect(html).not.toContain('agent.setupCodex');
    expect(html).not.toContain("codexCommand: $('inpCodexCommand')");
    expect(html).not.toContain('btnHermesOneClickSetup');
    expect(html).not.toContain('btnHermesConnectExisting');
  });

  it('auto-runs Codex setup before sending when the desired brain has fallen back to stub', () => {
    const panel = fs.readFileSync(copilotPanelPath, 'utf8');
    const preload = fs.readFileSync(shellPreloadPath, 'utf8');
    const main = fs.readFileSync(shellMainPath, 'utf8');

    expect(panel).toContain('function ensureCodexReadyBeforeSend');
    expect(panel).toContain('await ensureCodexReadyBeforeSend()');
    expect(panel).toContain('agent.runtimeStatus');
    expect(panel).toContain('progressRunId');
    expect(panel).toContain('agent.onCodexSetupProgress');
    expect(panel).toContain('activeCodexSetupRunId');
    expect(panel).toContain("runId.startsWith('launch-')");
    expect(panel).toContain('launch_complete');
    expect(panel).toContain('launch_failed');
    expect(panel).toContain('turnBusy = true');
    expect(panel).toContain('turnBusy = false');
    expect(panel).toContain('setupCodexWithLoginRecovery');
    expect(panel).toContain('requestShellUpdateCheckForCodexSetup');
    expect(panel).toContain('\\u5efa\\u8bae\\uff1a');
    expect(panel).not.toContain("Next: ' + next");
    expect(panel).toContain('function startCodexWaitHintTimer');
    expect(panel).toContain('clearCodexWaitHintTimer()');
    expect(panel).toContain('function rememberCodexProgress');
    expect(panel).toContain('Codex \\u6b63\\u5728\\u601d\\u8003');
    expect(panel).toContain('\\u7b49\\u5f85 Codex \\u8fd4\\u56de\\u6587\\u672c');
    expect(panel).toContain('rememberCodexProgress(ev)');
    expect(panel).toContain('startCodexWaitHintTimer()');
    expect(panel).toContain('check.nextAction');
    expect(panel).toContain('first.cloudAuthLoginRequired');
    expect(panel).toContain('switchToWorkbench()');
    expect(panel).toContain('waitForTeamAccountLogin(120000)');
    expect(panel).toContain('retryAfterLogin: true');
    expect(panel).toContain("desired !== 'codex'");
    expect(panel).toContain("active === 'codex' && probeOk");
    expect(panel).toContain('codexSetupFailureMessage');
    expect(panel).toContain('codexLastSetupRecoveryDetail');
    expect(panel).toContain('codexLastSetupReport');
    expect(panel).toContain('function codexLastSetupReportAllowsSend');
    expect(panel).toContain('trustedSetupReport: true');
    expect(panel).toContain('Click one-click Codex setup again; it will re-check this machine, install missing pieces, sync team identity, and test the conversation.');
    expect(panel).toContain('Click one-click Codex setup; it will repair the Codex command path or install missing pieces.');
    expect(panel).not.toContain('Codex CLI is selected but not available. Install/login Codex CLI or check settings.');
    expect(preload).toContain("setupCodex: (options) => timedInvoke('agent-codex-one-click-setup'");
    expect(preload).toContain("runtimeStatus: () => timedInvoke('agent-runtime-status')");
    expect(preload).toContain("checkShellUpdate: () => timedInvoke('shell-check-shell-update')");
    expect(preload).toContain("ipcRenderer.on('agent-codex-setup-progress'");
    expect(preload).toContain("return () => ipcRenderer.removeListener('agent-codex-setup-progress', listener)");
    expect(main).toContain("ipcMain.handle('agent-codex-one-click-setup'");
    expect(main).toContain('--assetcutter-codex-one-click-setup');
    expect(main).toContain('argvWantsCodexAutoSetup');
    expect(main).toContain('maybeRunCodexOneClickSetupFromLaunch');
    expect(main).toContain("source: 'launch_arg'");
    expect(main).toContain('launch_complete');
    expect(main).toContain('launch_failed');
    expect(main).toContain('openWorkbenchForCodexLaunchLogin');
    expect(main).toContain('waitForShellLoginForCodexLaunch');
    expect(main).toContain('launch_retry_after_login');
    expect(main).toContain("ipcMain.handle('agent-runtime-status'");
    expect(main).toContain('codexRuntime: buildCodexRuntimeStatus(settings)');
    expect(main).toContain("ipcMain.handle('shell-check-shell-update'");
    expect(main).toContain('companionUpdater.checkNow(true)');
    expect(main).toContain("mainWindow.webContents.send('agent-codex-setup-progress'");
    expect(main).toContain('runCodexOneClickSetup');
    expect(main).toContain('buildCodexSetupReport');
    expect(main).toContain('codexLastSetupReport');
    expect(main).toContain('desktopVersion: readDesktopShellPackageVersion()');
    expect(main).toContain('cloudIdentitySynced: Boolean(p.cloudIdentitySynced)');
    expect(main).toContain('conversationVerified: Boolean(p.conversationVerified)');
    expect(main).toContain('previousSetupReport');
    expect(main).toContain('previousSetupReport.conversationVerified');
    expect(main).toContain('previousSetupReport.cloudIdentitySynced');
    expect(main).toContain('const requireCloudIdentity = opts.cloudIdentity !== false');
    expect(main).toContain('const cloudIdentitySynced = Boolean(sync && sync.ok && !sync.skipped)');
    expect(main).toContain('shouldReplaceCodexSharedAuthUrl');
    expect(main).toContain('DEFAULT_AUTH_API_ORIGIN_PROD');
    expect(main).toContain("host === 'localhost'");
    expect(main).toContain("host === '127.0.0.1'");
    expect(main).toContain('shouldVerifyConversation && conversation && conversation.ok && !conversation.skipped');
    expect(main).toContain('nextAction');
    expect(main).toContain('codexCloudIdentityNextAction');
    expect(main).toContain('codexCliNextAction');
    expect(main).toContain("['install', '-g', '@openai/codex']");
    expect(main).toContain('installCodexWithNpmForSetup');
    expect(main).toContain('codexNpmGlobalPrefixForSetup');
    expect(main).toContain('setupNpmGlobalEnv');
    expect(main).toContain('NPM_CONFIG_PREFIX');
    expect(main).toContain('codex-npm-global');
    expect(main).toContain('install_codex_cli_portable');
    expect(main).toContain('firstAttempt: install');
    expect(main).toContain('fallback: codexNodeFallback');
    expect(main).toContain('installNodeRuntimeForSetup');
    expect(main).toContain('OpenJS.NodeJS.LTS');
    expect(main).toContain('NODE_LTS_DIST_URL');
    expect(main).toContain('resolveLatestNodeMsiForSetup');
    expect(main).toContain('downloadFileForSetup');
    expect(main).toContain('fetchTextViaPowerShellForSetup');
    expect(main).toContain('downloadFileViaPowerShellForSetup');
    expect(main).toContain("Invoke-WebRequest -Uri");
    expect(main).toContain("method: 'powershell'");
    expect(main).toContain('installNodeFromOfficialMsiForSetup');
    expect(main).toContain('installPortableNodeForSetup');
    expect(main).toContain('portableNodeRuntimeRootForSetup');
    expect(main).toContain('portableNodeNpmCandidatesForSetup');
    expect(main).toContain('resolveLatestNodeZipForSetup');
    expect(main).toContain('node_portable_download');
    expect(main).toContain('Expand-Archive');
    expect(main).toContain('SHASUMS256.txt');
    expect(main).toContain('sha256_mismatch');
    expect(main).toContain('msiexec.exe');
    expect(main).toContain("method: 'official_msi'");
    expect(main).toContain("method: 'portable_zip'");
    expect(main).toContain('resolveNpmCommandForSetup');
    expect(main).toContain('resolveCodexCommandForSetup');
    expect(main).toContain('knownWindowsCodexPaths');
    expect(main).toContain('setupCommandEnv');
    expect(main).toContain('setupToolPathDirs');
    expect(main).toContain('env: setupCommandEnv(setupToolPathDirs())');
    expect(main).toContain('resolve_existing_codex_cli');
    expect(main).toContain("source: 'existing'");
    expect(main).toContain('const shouldInstallCodex = opts.install !== false');
    expect(main).toContain('!existingCodex.ok');
    expect(main).toContain("detail.includes('\\ufffd') && detail.includes('codex')");
    expect(main).not.toContain("detail.includes('exited 1')");
    expect(panel).toContain('\\u5df2\\u5c1d\\u8bd5\\u7cfb\\u7edf npm \\u548c\\u4fbf\\u643a npm');

    const sendStart = panel.indexOf('async function sendMessage()');
    const setupCall = panel.indexOf('const setupReady = await ensureCodexReadyBeforeSend()', sendStart);
    const failureReturn = panel.indexOf('return;', setupCall);
    const sendCall = panel.indexOf('const r = await agent.send(outboundText, currentSessionId())', setupCall);
    expect(sendStart).toBeGreaterThanOrEqual(0);
    expect(setupCall).toBeGreaterThan(sendStart);
    expect(failureReturn).toBeGreaterThan(setupCall);
    expect(sendCall).toBeGreaterThan(failureReturn);
  });

  it('wires one-click Codex setup to the shell team identity route by default', () => {
    const main = fs.readFileSync(shellMainPath, 'utf8');
    const authApi = fs.readFileSync(authApiPath, 'utf8');

    expect(main).toContain('defaultCodexSharedAuthUrl');
    expect(main).toContain('/api/team/codex/auth');
    expect(main).toContain('codexSharedAuthEnabled: opts.cloudIdentity === false ? before.codexSharedAuthEnabled : true');
    expect(main).toContain('session.fromPartition(FIRST_PARTY_WEB_PARTITION)');
    expect(main).toContain('fetchCodexSharedAuthWithShellSession');
    expect(main).toContain('shellSessionCookieHeaderForCodexAuth');
    expect(main).toContain('Cookie: cookieHeader');
    expect(main).toContain('missing_shell_session_cookie');
    expect(main).toContain('cloudAuthLoginRequired');
    expect(main).toContain('cloudAuthRouteMissing');
    expect(main).toContain("startsWith('http_404')");
    expect(authApi).toContain("path === '/api/team/codex/auth'");
    expect(authApi).toContain('const user = await requireAuth(req, res)');
    expect(authApi).toContain('CODEX_SHARED_AUTH_JSON_BASE64');
    expect(authApi).toContain('validateTeamCodexAuthPayload');
    expect(authApi).toContain('invalid_codex_shared_auth');
  });

  it('opens Workbench login and retries Codex setup when cloud identity needs login', () => {
    const html = fs.readFileSync(shellIndexPath, 'utf8');
    const panel = fs.readFileSync(copilotPanelPath, 'utf8');

    expect(html).not.toContain('setupCodexWithLoginRecoveryUi');
    expect(html).not.toContain('btnCopyCodexSetupReport');
    expect(html).toContain('async function openWorkbenchLoginUi');
    expect(panel).toContain('setup = await setupCodexWithLoginRecovery({');
    expect(panel).toContain('verifyConversation: true');
    expect(panel).toContain('verifyConversation: false');
    expect(panel).toContain('cloudAuthRouteMissing');
  });

  it('keeps a release readiness check for Codex one-click setup', () => {
    const pkg = fs.readFileSync(packageJsonPath, 'utf8');
    const script = fs.readFileSync(codexOneClickCheckPath, 'utf8');
    const exportScript = fs.readFileSync(codexAuthEnvExportPath, 'utf8');
    const authEnvCheckScript = fs.readFileSync(codexAuthEnvCheckPath, 'utf8');
    const productionScript = fs.readFileSync(codexProductionCheckPath, 'utf8');
    const cleanMachineScript = fs.readFileSync(codexCleanMachineCheckPath, 'utf8');
    const cleanMachinePs1 = fs.readFileSync(codexCleanMachinePs1Path, 'utf8');
    const uploadManifestScript = fs.readFileSync(desktopUploadManifestPath, 'utf8');
    const publishScript = fs.readFileSync(desktopPublishPath, 'utf8');
    const finalizeScript = fs.readFileSync(codexFinalizeProductionPath, 'utf8');
    const releaseCheck = fs.readFileSync(companionReleaseCheckPath, 'utf8');
    const renderYaml = fs.readFileSync(renderYamlPath, 'utf8');

    expect(pkg).toContain('"companion:codex-one-click-check": "node scripts/check-codex-one-click-readiness.mjs"');
    expect(pkg).toContain('"companion:codex-auth-env": "node scripts/export-codex-shared-auth-env.mjs"');
    expect(pkg).toContain('"companion:codex-auth-env:check": "node scripts/validate-codex-shared-auth-env.mjs"');
    expect(pkg).toContain('"companion:codex-render-auth-env:apply": "node scripts/apply-codex-shared-auth-to-render.mjs"');
    expect(pkg).toContain('"companion:codex-production-check": "node scripts/verify-codex-one-click-production.mjs"');
    expect(pkg).toContain('"companion:codex-clean-machine-check": "node scripts/verify-codex-clean-machine.mjs"');
    expect(pkg).toContain('"companion:desktop-upload-manifest": "node scripts/prepare-companion-desktop-upload-manifest.mjs"');
    expect(pkg).toContain('"companion:desktop-publish": "node scripts/publish-companion-desktop-artifact.mjs"');
    expect(pkg).toContain('"companion:codex-finalize-production": "node scripts/finalize-codex-one-click-production.mjs"');
    expect(script).toContain('Codex one-click readiness check');
    expect(script).toContain('CODEX_SHARED_AUTH_JSON_BASE64');
    expect(script).toContain('CODEX_SHARED_AUTH_JSON');
    expect(script).toContain('Local companion health');
    expect(script).toContain('Cloud Codex identity route');
    expect(script).toContain('--conversation-smoke');
    expect(script).toContain('Codex real conversation smoke');
    expect(script).toContain('assetcutter-codex-ready');
    expect(script).toContain('codex_conversation_smoke');
    expect(script).toContain('setupToolPathDirs');
    expect(script).toContain('knownWindowsCommandPaths');
    expect(script).toContain('commandVersionWithKnownPaths');
    expect(script).toContain('resolveCodexCommandForSmoke');
    expect(script).toContain('LOCALAPPDATA');
    expect(script).toContain('AssetCutterCompanion');
    expect(script).toContain('Desktop package includes Codex setup files');
    expect(script).toContain('Built desktop package is Codex-only');
    expect(script).toContain('desktop_built_asar_codex_only');
    expect(script).toContain('built app.asar contains Codex-only agent files');
    expect(script).toContain('agentSettingsUiIsCodexOnly');
    expect(script).toContain('Agent settings UI is Codex-only');
    expect(script).toContain('agent_settings_ui_codex_only');
    expect(script).toContain('web and desktop Agent settings expose Codex-only controls');
    expect(script).toContain('desktopOneClickHasCleanMachineFallbacks');
    expect(script).toContain('Desktop one-click setup has clean-machine fallbacks');
    expect(script).toContain('desktop_one_click_clean_machine_fallbacks');
    expect(script).toContain('one-click setup includes Node/npm/Codex clean-machine fallbacks');
    expect(script).toContain('codex-npm-global');
    expect(script).toContain('install_codex_cli_portable');
    expect(script).toContain('Invoke-WebRequest -Uri');
    expect(script).toContain('codex-auth-sync.cjs');
    expect(script).toContain('brain-adapters/codex.cjs');
    expect(script).toContain('forbidden external agent files included');
    expect(script).toContain('hermes-official-host.cjs');
    expect(script).toContain('brain-adapters/openai_compat.cjs');
    expect(script).toContain('route exists, login or shared identity is required');
    expect(releaseCheck).toContain('$routeExistsWithoutCookie');
    expect(releaseCheck).toContain('pass -CodexAuthCookie to verify logged-in payload');
    expect(renderYaml).toContain('CODEX_SHARED_AUTH_JSON_BASE64');
    expect(renderYaml).toContain('CODEX_SHARED_AUTH_JSON');
    expect(exportScript).toContain('.env.codex-shared-auth.local');
    expect(exportScript).toContain('Secret value was written to the output file, not printed.');
    expect(exportScript).toContain('JSON.parse(raw)');
    expect(authEnvCheckScript).toContain('Codex shared auth env is valid');
    expect(authEnvCheckScript).toContain('CODEX_SHARED_AUTH_JSON_BASE64');
    expect(finalizeScript).toContain('Validate Codex shared auth env shape');
    expect(productionScript).toContain('Codex one-click production verification');
    expect(productionScript).toContain('/api/team/codex/auth');
    expect(productionScript).toContain('validateCodexAuthPayload');
    expect(productionScript).toContain('valid Codex auth payload');
    expect(productionScript).toContain('/api/companion-artifacts/electron-updater/win32/stable/latest.yml');
    expect(productionScript).toContain('Desktop update feed contains target version');
    expect(productionScript).toContain('/api/companion-artifacts/latest?kind=desktop_shell&platform=win32&channel=stable');
    expect(productionScript).toContain('desktop_artifact_clean_machine_acceptance');
    expect(productionScript).toContain('validateCleanMachineAcceptanceNotes');
    expect(productionScript).toContain('#cleanMachineAcceptanceBundleR2Key:');
    expect(productionScript).toContain('#cleanMachineAcceptanceBundleFiles:');
    expect(productionScript).toContain('README-clean-machine.txt');
    expect(cleanMachineScript).toContain('Codex clean-machine acceptance');
    expect(cleanMachineScript).toContain('scripts/check-codex-one-click-readiness.mjs');
    expect(cleanMachineScript).toContain('scripts/verify-codex-one-click-production.mjs');
    expect(cleanMachineScript).toContain('--conversation-smoke');
    expect(cleanMachineScript).toContain('CODEX_SHARED_AUTH_CHECK_COOKIE');
    expect(cleanMachineScript).toContain('--out');
    expect(cleanMachineScript).toContain('defaultReportPath');
    expect(cleanMachineScript).toContain('writeReport');
    expect(cleanMachineScript).toContain('reportPath');
    expect(cleanMachineScript).toContain('readDesktopOneClickSetupReport');
    expect(cleanMachineScript).toContain('readDesktopOneClickSetupReport(agentSettingsPath, desktopVersion)');
    expect(cleanMachineScript).toContain('codexLastSetupReport');
    expect(cleanMachineScript).toContain('setupReport.desktopVersion');
    expect(cleanMachineScript).toContain('setupReport.conversationVerified');
    expect(cleanMachineScript).toContain('setupReport.cloudIdentitySynced');
    expect(cleanMachineScript).toContain('did not record cloud identity sync');
    expect(cleanMachineScript).toContain('did not record an in-setup conversation verification');
    expect(cleanMachineScript).toContain('expected ${targetVersion}');
    expect(cleanMachineScript).toContain('Desktop one-click Codex setup report');
    expect(cleanMachineScript).toContain('--agent-settings');
    expect(cleanMachineScript).toContain('buildNextActions');
    expect(cleanMachineScript).toContain('nextActions');
    expect(cleanMachineScript).toContain('Next actions:');
    expect(cleanMachineScript).toContain('Publish/register the fresh desktop installer');
    expect(cleanMachineScript).toContain('-AutoCodexSetup');
    expect(cleanMachineScript).toContain('clean-machine evidence is complete');
    expect(cleanMachineScript).toContain('diagnostic report collected; warnings remain');
    expect(cleanMachineScript).toContain('strict');
    expect(cleanMachinePs1).toContain('param(');
    expect(cleanMachinePs1).toContain('Read-OneClickReport');
    expect(cleanMachinePs1).toContain('Get-CompanionCodexPathCandidates');
    expect(cleanMachinePs1).toContain('codex-npm-global\\codex.cmd');
    expect(cleanMachinePs1).toContain('Find-CompanionInstaller');
    expect(cleanMachinePs1).toContain('Get-DesktopVersionFromInstallerName');
    expect(cleanMachinePs1).toContain('AssetCutterCompanion-(\\d+\\.\\d+\\.\\d+)-.+-x64\\.exe');
    expect(cleanMachinePs1).toContain('AssetCutterCompanion-*-x64.exe');
    expect(cleanMachinePs1).toContain('LaunchInstaller');
    expect(cleanMachinePs1).toContain('AutoCodexSetup');
    expect(cleanMachinePs1).toContain('rerun this script with -AutoCodexSetup');
    expect(cleanMachinePs1).toContain('CompanionWaitSeconds');
    expect(cleanMachinePs1).toContain('CodexSetupWaitSeconds');
    expect(cleanMachinePs1).toContain('Wait-CompanionHealth');
    expect(cleanMachinePs1).toContain('Find-InstalledCompanionApp');
    expect(cleanMachinePs1).toContain('Start-InstalledCompanionApp');
    expect(cleanMachinePs1).toContain('--assetcutter-codex-one-click-setup');
    expect(cleanMachinePs1).toContain('Wait-CodexOneClickSetupReport');
    expect(cleanMachinePs1).toContain('Test-OneClickReportNeedsLoginWait');
    expect(cleanMachinePs1).toContain('Timed out waiting for Workbench sign-in');
    expect(cleanMachinePs1).toContain('desktop_one_click_setup_wait');
    expect(cleanMachinePs1).toContain('StartedAfter');
    expect(cleanMachinePs1).toContain('autoSetupStartedAt');
    expect(cleanMachinePs1).toContain('Codex one-click setup failed at');
    expect(cleanMachinePs1).toContain('desktop_app_launch');
    expect(cleanMachinePs1).toContain('local_companion_wait');
    expect(cleanMachinePs1).toContain('Local companion health');
    expect(cleanMachinePs1).toContain('Desktop installer package');
    expect(cleanMachinePs1).toContain('Test-CodexAuthPayload');
    expect(cleanMachinePs1).toContain('authJsonBase64');
    expect(cleanMachinePs1).toContain('valid Codex auth payload');
    expect(cleanMachinePs1).toContain('codexLastSetupReport');
    expect(cleanMachinePs1).toContain('$report.desktopVersion');
    expect(cleanMachinePs1).toContain('$report.conversationVerified');
    expect(cleanMachinePs1).toContain('$report.cloudIdentitySynced');
    expect(cleanMachinePs1).toContain('expected $DesktopVersion');
    expect(cleanMachinePs1).toContain('Next actions:');
    expect(cleanMachinePs1).toContain('Publish/register the fresh desktop installer');
    expect(cleanMachinePs1).toContain('Codex clean-machine acceptance');
    expect(uploadManifestScript).toContain('Admin registration payload');
    expect(uploadManifestScript).toContain('blockMapR2Key');
    expect(uploadManifestScript).toContain("hashFile(exePath, 'sha512')");
    expect(uploadManifestScript).toContain('.sort((a, b) => b.mtimeMs - a.mtimeMs');
    expect(uploadManifestScript).toContain('assertInstallerFresh');
    expect(uploadManifestScript).toContain('assertBuiltAsarCodexOnly');
    expect(uploadManifestScript).toContain('Built app.asar still contains non-Codex agent files');
    expect(uploadManifestScript).toContain('asarCodexOnly');
    expect(uploadManifestScript).toContain('cleanMachineAcceptanceScript');
    expect(uploadManifestScript).toContain('cleanMachineAcceptance');
    expect(uploadManifestScript).toContain('cleanMachineAcceptanceBundle');
    expect(uploadManifestScript).toContain('clean-machine-acceptance.zip');
    expect(uploadManifestScript).toContain('bundleFiles');
    expect(uploadManifestScript).toContain('README-clean-machine.txt');
    expect(uploadManifestScript).toContain('-LaunchInstaller -AutoCodexSetup -Strict');
    expect(uploadManifestScript).toContain('codex-clean-machine-report-*.json');
    expect(uploadManifestScript).toContain('desktopSourceFilesForFreshness');
    expect(uploadManifestScript).toContain('--allow-stale-installer');
    expect(uploadManifestScript).toContain('Repack before publishing');
    expect(publishScript).toContain('COMPANION_ADMIN_COOKIE');
    expect(publishScript).toContain('/api/admin/companion-artifacts/upload-url');
    expect(publishScript).toContain('/api/admin/companion-artifacts');
    expect(publishScript).toContain('cleanMachineAcceptanceScript');
    expect(publishScript).toContain('cleanMachineAcceptanceNotes');
    expect(publishScript).toContain('#cleanMachineAcceptance:required');
    expect(publishScript).toContain('#cleanMachineAcceptanceBundleR2Key:');
    expect(publishScript).toContain('#cleanMachineAcceptanceLocalCommand:');
    expect(publishScript).toContain('upload clean-machine acceptance script');
    expect(publishScript).toContain('upload clean-machine acceptance bundle');
    expect(publishScript).toContain('Dry-run extra upload');
    expect(publishScript).toContain('--dry-run');
    expect(publishScript).toContain('function readDesktopVersion()');
    expect(publishScript).toContain('function defaultManifestPath()');
    expect(publishScript).toContain('companion-desktop/package.json');
    expect(publishScript).toContain('defaultManifestPath()');
    expect(publishScript).not.toContain('dist-out-0211');
    expect(finalizeScript).toContain('Codex one-click production finalizer');
    expect(finalizeScript).toContain("args.has('--publish')");
    expect(finalizeScript).toContain("args.has('--skip-local-smoke')");
    expect(finalizeScript).toContain("args.has('--apply-render-auth')");
    expect(finalizeScript).toContain("args.has('--deploy-render-auth')");
    expect(finalizeScript).toContain("args.has('--wait-render-auth-deploy')");
    expect(finalizeScript).toContain("args.has('--require-clean-machine')");
    expect(finalizeScript).toContain('cleanMachineRequired');
    expect(finalizeScript).toContain('printCleanMachineNextActions');
    expect(finalizeScript).toContain('verify-codex-clean-machine.ps1 -LaunchInstaller -AutoCodexSetup -Strict');
    expect(finalizeScript).toContain('printPublishNextActions');
    expect(finalizeScript).toContain('printSharedAuthNextActions');
    expect(finalizeScript).toContain('Publish is not the final acceptance step');
    expect(finalizeScript).toContain('--clean-machine-report');
    expect(finalizeScript).toContain('validateCleanMachineReport');
    expect(finalizeScript).toContain('Validate clean-machine acceptance report');
    expect(finalizeScript).toContain('Clean-machine acceptance report');
    expect(finalizeScript).toContain('companion:codex-one-click-check');
    expect(finalizeScript).toContain('--conversation-smoke');
    expect(finalizeScript).toContain('Verify local Codex one-click readiness with real conversation');
    expect(finalizeScript).toContain('buildProductionArgs');
    expect(finalizeScript).toContain('--auth-env-file');
    expect(finalizeScript).toContain('.env.codex-shared-auth.local');
    expect(finalizeScript).toContain('Validate Codex shared auth env file shape');
    expect(finalizeScript).toContain('sharedAuthEnvFile');
    expect(finalizeScript).toContain('renderApiKey');
    expect(finalizeScript).toContain('applyRenderAuth');
    expect(finalizeScript).toContain('deployRenderAuth');
    expect(finalizeScript).toContain('waitRenderAuthDeploy');
    expect(finalizeScript).toContain('companion:codex-render-auth-env:apply');
    expect(finalizeScript).toContain('Apply Codex shared auth env to Render and trigger deploy');
    expect(finalizeScript).toContain('CODEX_SHARED_AUTH_* values into Render auth-api');
    expect(finalizeScript).toContain('authCheckCookie');
    expect(finalizeScript).toContain('CODEX_SHARED_AUTH_CHECK_COOKIE');
    expect(finalizeScript).toContain('Verify production after publish (strict)');
    expect(finalizeScript).toContain("buildProductionArgs(true)");
    expect(finalizeScript).toContain('companion:desktop-upload-manifest');
    expect(finalizeScript).toContain('companion:desktop-publish');
    expect(finalizeScript).toContain('companion:codex-production-check');
    expect(finalizeScript).toContain('Missing admin cookie');
    const releasePackScript = fs.readFileSync(path.resolve(process.cwd(), 'scripts/companion-release-pack.ps1'), 'utf8');
    expect(releasePackScript).toContain('verify-codex-clean-machine.ps1');
    expect(releasePackScript).toContain('README-clean-machine.txt');
    expect(releasePackScript).toContain('cloudIdentitySynced=true');
    expect(releasePackScript).toContain('clean-machine-acceptance.zip');
    expect(releasePackScript).toContain('Compress-Archive');
  });

  it('keeps the Agent settings panel focused on Codex only', () => {
    const html = fs.readFileSync(shellIndexPath, 'utf8');
    const preload = fs.readFileSync(shellPreloadPath, 'utf8');
    const pkg = fs.readFileSync(packageJsonPath, 'utf8');

    expect(html).not.toContain('Copilot currently uses Codex only');
    expect(html).not.toContain('btnHermesOneClickSetup');
    expect(html).not.toContain('btnHermesConnectExisting');
    expect(html).not.toContain('npm run agent:init');
    expect(html).not.toContain('npm run agent:cli');
    expect(preload).not.toContain('hermesGatewaySetup');
    expect(preload).not.toContain('companionConnect');
    expect(pkg).not.toContain('"companion:connect"');
    expect(pkg).not.toContain('"companion:connect:detect"');
    expect(pkg).not.toContain('"dev:hermes-gateway"');
  });

  it('keeps the web Agent settings focused on Codex only', () => {
    const rootHtml = fs.readFileSync(rootIndexPath, 'utf8');
    const shellHtml = fs.readFileSync(shellIndexPath, 'utf8');
    const app = fs.readFileSync(path.resolve(process.cwd(), 'App.tsx'), 'utf8');

    expect(rootHtml).toContain('/index.tsx');
    expect(shellHtml).not.toContain('Copilot currently uses Codex only');
    for (const text of [rootHtml, shellHtml, app]) {
      expect(text).not.toContain('btnHermesOneClickSetup');
      expect(text).not.toContain('btnHermesConnectExisting');
      expect(text).not.toContain('hermesGatewaySetup');
      expect(text).not.toContain('companionConnect');
      expect(text).not.toContain('openai_compat');
      expect(text).not.toContain('claude_code');
      expect(text).not.toContain('npm run agent:init');
      expect(text).not.toContain('npm run agent:cli');
    }
  });

  it('shows workbench login diagnostics in the e2e entrance state', () => {
    const html = fs.readFileSync(shellIndexPath, 'utf8');
    const main = fs.readFileSync(shellMainPath, 'utf8');
    const preload = fs.readFileSync(shellPreloadPath, 'utf8');

    expect(html).not.toContain('formatAgentMcpE2eAuthDiagnostics');
    expect(html).not.toContain('id="agentMcpWorkbenchEntranceDetail"');
    expect(html).not.toContain('id="agentWorkflowPromotionCard"');
    expect(html).toContain('formatShellAccountDiagnosticLine');
    expect(html).toContain('Waiting for Workbench sign-in: ${remaining}s remaining');
    expect(html).not.toContain('id="btnOpenWorkbenchLogin"');
    expect(preload).toContain("workflowPromotionPreflight: (options) => timedInvoke('agent-workflow-promotion-preflight'");
expect(preload).toContain("workflowPromotionDrafts: () => timedInvoke('agent-workflow-promotion-drafts'");
    expect(main).toContain("ipcMain.handle('agent-workflow-promotion-preflight'");
    expect(main).toContain("ipcMain.handle('agent-workflow-promotion-drafts'");
    expect(main).toContain('listWorkflowPromotionDraftSummaries');
    expect(main).toContain('listSkillEntries(skillsRoot)');
    expect(main).toContain("policyDecision: 'copilot_ui_admin_confirm'");
    expect(main).toContain("adminConfirmationSource: 'copilot_ui'");
    expect(main).toContain("auditRecordWritten: true");
  });

  it('exposes a local shell account status card backed by the shared team partition', () => {
    const html = fs.readFileSync(shellIndexPath, 'utf8');
    const main = fs.readFileSync(shellMainPath, 'utf8');
    const preload = fs.readFileSync(shellPreloadPath, 'utf8');
    const scriptHubClient = fs.readFileSync(scriptHubClientPath, 'utf8');

    expect(html).not.toContain('id="shellAccountCard"');
    expect(html).not.toContain('id="btnOpenWorkbenchLogin"');
    expect(html).not.toContain('id="btnShellAccountWaitLoginE2e"');
    expect(html).not.toContain('id="btnRefreshShellAccount"');
    expect(html).toContain('loadShellAccountStatusUi');
    expect(html).toContain('openWorkbenchLoginUi');
    expect(preload).toContain("accountStatus: () => timedInvoke('shell-account-status')");
    expect(main).toContain("const FIRST_PARTY_WEB_PARTITION = TEAM_WEB_PARTITION");
    expect(main).toContain('LEGACY_FIRST_PARTY_WEB_PARTITIONS');
    expect(main).toContain("['persist:assetcutter-workbench', 'persist:assetcutter-script-hub']");
    expect(main).toContain('migrateLegacyFirstPartyCookies');
    expect(main).toContain("skippedReason = 'target_has_auth_cookie'");
    expect(main).toContain('electronCookieSetDetails');
    expect(main).toContain('summarizeShellAccountForAgent');
    expect(main).toContain('account: shellAccount');
    expect(main).toContain('Use ac.workbench.ensure_ready');
    expect(main).toContain('readShellAccountStatus');
    expect(main).toContain("ipcMain.handle('shell-account-status'");
    expect(main).toContain('partition: FIRST_PARTY_WEB_PARTITION');
    expect(main).toContain('function ensureWorkbenchBrowserView()');
    expect(main).toMatch(/function ensureWorkbenchBrowserView\(\)[\s\S]*?webPreferences:\s*\{[\s\S]*?partition:\s*FIRST_PARTY_WEB_PARTITION/);
    expect(main).not.toContain('function ensureScriptsBrowserView()');
    expect(main).not.toContain('scriptsBrowserView');
    expect(fs.readFileSync(path.resolve(process.cwd(), 'companion-desktop/shell-rooms.cjs'), 'utf8')).toContain(
      "if (v === 'scripts') return 'workflow'",
    );
    expect(main).toContain("credentials: 'include'");
    expect(main).toContain('const shellAccount = await readShellAccountStatus();');
    expect(main).toContain('summarizeWorkbenchE2eEntrance');
    expect(main).toContain('mcpWorkbenchLastE2e');
    expect(main).toContain('buildAgentMcpEntranceStatus');
    expect(main).toContain('mcpEntranceStatus');
    expect(main).toContain('buildAgentMcpEntranceBlockers');
    expect(main).toContain("require('./agent-blocker-actions.cjs')");
    expect(main).toContain('workbenchLoginActions()');
    expect(main).toContain('workflowPromotionActions()');
    expect(main).toContain('usageGovernanceActions()');
    expect(main).toContain('const usageCloudDraft = usage.cloudDraft');
    expect(main).toContain('missingGates: usageMissingGates');
    expect(main).toContain('cloudDraft: usageCloudDraft');
    expect(main).toContain('blockedBy: Array.isArray(usageCloudDraft.blockedBy)');
    expect(main).toContain('teamEntranceReady');
    expect(main).toContain('teamEntrancePhase');
    expect(main).toContain('teamEntranceBlockers');
    expect(main).toContain('governance_blocked');
    expect(main).toContain('workbench_blocked');
    expect(main).toContain('summarizeWorkflowPublicationState');
    expect(main).toContain('summarizeCopilotUsageAudit({ days: 1, limit: 5000 })');
    expect(main).toContain('readCopilotUsageQuotaPolicy');
    expect(main).toContain("ipcMain.handle('agent-usage-upload-cloud-draft'");
    expect(main).toContain('uploadCopilotUsageCloudDraft(options');
    expect(main).toContain("require('./agent-usage-cloud-draft.cjs')");
    expect(main.indexOf("code: 'AGENT_USAGE_UPLOAD_NO_EVENTS'")).toBeLessThan(
      main.indexOf("code: 'AGENT_AUTH_REQUIRED'"),
    );
    expect(main.indexOf('if (dryRun)')).toBeLessThan(main.indexOf("code: 'AGENT_AUTH_REQUIRED'"));
    expect(preload).toContain("usageUploadCloudDraft: (options) => timedInvoke('agent-usage-upload-cloud-draft'");
    expect(preload).toContain("usageQuotaPolicyProbe: () => timedInvoke('agent-usage-quota-policy-probe'");
    expect(main).toContain("ipcMain.handle('agent-usage-quota-policy-probe'");
    expect(main).toContain('/api/usage/policy');
    expect(main).toContain('summarizeWorkbenchEntranceState');
    expect(main).toContain('authOrigin: account.authOrigin');
    expect(main).toContain('siteOrigin: account.siteOrigin');
    expect(main).toContain('shellAccount,');
    expect(main).toContain('mcpWorkbenchLastE2e,');
    expect(main).not.toContain("partition: 'persist:assetcutter-script-hub'");
    expect(main).not.toContain("partition: 'persist:assetcutter-workbench'");
    expect(scriptHubClient).toContain("const SCRIPT_HUB_PARTITION = TEAM_WEB_PARTITION");
    expect(scriptHubClient).not.toContain("const SCRIPT_HUB_PARTITION = 'persist:assetcutter-script-hub'");
    expect(html).toContain('renderShellAccountStatus');
  });

  it('surfaces workbench login readiness in the right-side Copilot entrance', () => {
    const panel = fs.readFileSync(copilotPanelPath, 'utf8');

    expect(panel).toContain('lastAccountSnapshot');
    expect(panel).toContain('lastWorkbenchEntranceSnapshot');
    expect(panel).toContain('loadTeamAccountStatus');
    expect(panel).toContain('workbenchEntranceFromSettings');
    expect(panel).toContain('workbenchAcceptanceFromSettings');
    expect(panel).toContain('teamEntranceFromSettings');
    expect(panel).toContain('lastTeamEntranceSnapshot');
    expect(panel).toContain('blockersFromSettings');
    expect(panel).toContain('runWorkbenchEntranceValidation');
    expect(panel).toContain('agent.mcpWorkbenchE2e');
    expect(panel).toContain('waitForTeamAccountLogin');
    expect(panel).toContain('await waitForTeamAccountLogin(120000)');
    expect(panel).toContain('recoveryWaitMs: 30000');
    expect(panel).toContain('\\u8fd0\\u884c\\u5de5\\u4f5c\\u53f0\\u9a8c\\u6536');
    expect(panel).toContain('\\u767b\\u5f55\\u540e\\u9a8c\\u6536');
    expect(panel).toContain("if (info.kind === 'workbench-auth')");
    expect(panel).toContain('shell.accountStatus');
    expect(panel).toContain('mcpEntranceStatus');
    expect(panel).toContain('workbenchEntrance');
    expect(panel).toContain('workbenchAcceptance');
    expect(panel).toContain('mcpEntranceStatus.blockers');
    expect(panel).toContain('opts.blockers');
    expect(panel).toContain('opts.teamEntrance');
    expect(panel).toContain('teamEntrancePhase');
    expect(panel).toContain('teamEntranceReady');
    expect(panel).toContain('governance_blocked');
    expect(panel).toContain('workbench_blocked');
    expect(panel).toContain('\\u56e2\\u961f\\u53d1\\u5e03\\u6cbb\\u7406');
    expect(panel).toContain('blockerList');
    expect(panel).toContain('formatBlockerActions');
    expect(panel).toContain('runCopilotBlockerAction');
    expect(panel).toContain('appendBlockerActionButtons');
    expect(panel).toContain('blockerActionKey');
    expect(panel).toContain('formatRequiredInputs');
    expect(panel).toContain('formatTeamAccountDiagnostics');
    expect(panel).toContain("'Account: ' + formatTeamAccountDiagnostics(account)");
    expect(panel).toContain('formatTeamAccountDiagnostics(login)');
    expect(panel).toContain('action.requiredInputs');
    expect(panel).toContain('inputs=${names.join');
    expect(panel).toContain('requiredInputLine');
    expect(panel).toContain('action started: ${label}');
    expect(panel).toContain('action finished: ${label}');
    expect(panel).toContain('action needs input: ${label}');
    expect(panel).toContain('action failed: ${label}');
    expect(panel).toContain('blockerActions');
    expect(panel).toContain("'Actions: ' + blockerActions.join");
    expect(panel).toContain("command.includes('smoke:agent-mcp:e2e:open-login-wait')");
    expect(panel).toContain("command.includes('smoke:agent-mcp:e2e:wait-login')");
    expect(panel).toContain("tool === 'ac.usage.probe_quota_policy'");
    expect(panel).toContain("tool === 'ac.usage.upload_cloud_draft'");
    expect(panel).toContain("tool === 'ac.workflow.promote_workbench_preset'");
    expect(panel).toContain('appendBlockerActionButtons(actions, blockers)');
    expect(panel).toContain('workbench_login_required');
    expect(panel).toContain('workflow_promotion_draft_only');
    expect(panel).toContain('usage_governance_local_only');
    expect(panel).toContain('workflowMissing');
    expect(panel).toContain('Workflow gates:');
    expect(panel).toContain('workflowPublicationFromSettings');
    expect(panel).toContain('workflowPublication');
    expect(panel).toContain('promotionPreflightEvidence');
    expect(panel).toContain('Workflow evidence:');
    expect(panel).toContain('deleted draft');
    expect(panel).toContain("' stale ' + (latestPromotionEvidence.staleReason");
    expect(panel).toContain('usageBlocker');
    expect(panel).toContain('Usage upload:');
    expect(panel).toContain('usageBlocker.cloudDraft.uploadPlan.tool');
    expect(panel).toContain('Usage quota:');
    expect(panel).toContain('cloudQuotaEnforced ?');
    expect(panel).toContain('Usage policy probe:');
    expect(panel).toContain('usageBlockedBy');
    expect(panel).toContain('Usage blockers:');
    expect(panel).toContain('usageAuditFromSettings');
    expect(panel).toContain('usageAudit');
    expect(panel).toContain('governanceEvidence');
    expect(panel).toContain('Usage evidence:');
    expect(panel).toContain('latestUsageEvidence.exitReady');
    expect(panel).toContain('usageRemaining');
    expect(panel).toContain('Workbench acceptance:');
    expect(panel).toContain('admin approval');
    expect(panel).toContain('.slice(0, 3)');
    expect(panel).toContain('if (ready && blockers.length)');
    expect(panel).not.toContain('if (ready && blockers.length && !entranceReady)');
    expect(panel).toContain("\\u5de5\\u4f5c\\u53f0\\u767b\\u5f55\\u672a\\u5b8c\\u6210");
    expect(panel).toContain("Workflow \\u4ecd\\u662f\\u8349\\u7a3f\\u9636\\u6bb5");
    expect(panel).toContain('entranceReady');
    expect(panel).toContain("entranceStatus !== 'login_required'");
    expect(panel).toContain('e2e_missing');
    expect(panel).toContain("\\u5de5\\u4f5c\\u53f0\\u5f85\\u767b\\u5f55");
    expect(panel).toContain('\\u6253\\u5f00\\u8bbe\\u7f6e\\u9a8c\\u6536');
    expect(panel).toContain("\\u6253\\u5f00\\u5de5\\u4f5c\\u53f0\\u767b\\u5f55");
    expect(panel).toContain("Copilot \\u5927\\u8111\\u5df2\\u5c31\\u7eea");
    expect(panel).toContain('workflowPublication,');
    expect(panel).toContain('usageAudit,');
  });

  it('passes sidebar inset as an object so collapsed width 0 is not eaten as IPC timeout', () => {
    const preload = fs.readFileSync(shellPreloadPath, 'utf8');
    const main = fs.readFileSync(shellMainPath, 'utf8');

    expect(preload).toContain("timedInvoke('shell-workbench-sidebar-inset', { px:");
    expect(preload).not.toMatch(
      /setWorkbenchSidebarInsetPx:\s*\(px\)\s*=>\s*timedInvoke\('shell-workbench-sidebar-inset',\s*px\)/,
    );
    expect(main).toContain("payload.px");
    expect(main).toContain("shell-workbench-sidebar-inset");
  });

  it('hides Copilot completely when collapsed and puts the toggle next to window controls', () => {
    const panel = fs.readFileSync(copilotPanelPath, 'utf8');
    const html = fs.readFileSync(shellIndexPath, 'utf8').replace(/\r\n/g, '\n');
    const main = fs.readFileSync(shellMainPath, 'utf8');

    expect(html).not.toContain('id="copilot-toggle"');
    expect(html).toMatch(
      /id="btnDshPaneToggle"[\s\S]*?id="btnTrafficMin"/,
    );
    expect(html).not.toMatch(
      /<aside class="shell-copilot"[\s\S]*?id="copilot-toggle"/,
    );
    expect(html).toContain('body.shell-copilot-collapsed aside.shell-copilot');
    expect(html).toContain('visibility: hidden');
    expect(html).toContain('body.shell-sidebar-collapsed nav.shell-sidebar');
    expect(html).not.toContain('flex: 0 0 48px');
    expect(panel).toContain('const COPILOT_COLLAPSED_WIDTH = 0');
    expect(main).toContain('const SHELL_COPILOT_WIDTH_COLLAPSED = 0');
  });

  it('keeps the right-side Copilot aligned to the long-work P0 home screen', () => {
    const panel = fs.readFileSync(copilotPanelPath, 'utf8');
    const html = fs.readFileSync(shellIndexPath, 'utf8');
    const main = fs.readFileSync(shellMainPath, 'utf8');
    const preload = fs.readFileSync(shellPreloadPath, 'utf8');

    expect(panel).toContain('showMemberOnboardCard');
    expect(panel).toContain('showLongWorkHomeCard');
    expect(panel).toContain('loadWorkbenchContextSnapshot');
    expect(panel).toContain('refreshShellCopilotPerceptionBar');
    expect(panel).toContain('updateShellCopilotPerceptionBar');
    expect(panel).toContain('@typedef {Object} CopilotRuntimeState');
    expect(panel).toContain('function buildCopilotRuntimeState');
    expect(panel).toContain('function renderShellCopilotPerceptionBar');
    expect(panel).toContain('function buildConfirmPerceptionSummary');
    expect(panel).toContain('function buildActiveTaskState');
    expect(panel).toContain('const COPILOT_TIMELINE_LIMIT = 50');
    expect(panel).toContain('desktopObservationState = {');
    expect(panel).toContain('function updateDesktopObservationUi');
    expect(panel).toContain('function setDesktopObservationState');
    expect(panel).toContain('desktopObservationScopeLabel');
    expect(panel).toContain('permissionGranted: false');
    expect(panel).toContain('cacheFrameCount: 0');
    expect(panel).toContain('function applyDesktopObservationStatus');
    expect(panel).toContain('function refreshDesktopObservationStatus');
    expect(panel).toContain('function startDesktopObservationRuntime');
    expect(panel).toContain('function buildDesktopObservationRuntimeSummary');
    expect(panel).toContain('rawFrameRequiresConfirmation: true');
    expect(panel).toContain('desktopObservation,');
    expect(panel).toContain('function refreshCopilotObservationAfterAction');
    expect(panel).toContain('观察已刷新：');
    expect(panel).toContain('观察刷新失败：');
    expect(panel).toContain("refreshCopilotObservationAfterAction('任务完成', 'done')");
    expect(panel).toContain("refreshCopilotObservationAfterAction('任务停止', 'cancelled')");
    expect(panel).toContain("refreshCopilotObservationAfterAction('任务失败', 'failed')");
    expect(panel).toContain('foregroundApp');
    expect(panel).toContain('foregroundWindowTitle');
    expect(panel).toContain('lastFrameAt');
    expect(panel).toContain('refreshDesktopObservationStatus({ emitLatestFrame: true })');
    expect(panel).toContain('desktop.observe.frame');
    expect(panel).toContain('desktopObservationStop');
    expect(main).toContain('const DESKTOP_OBSERVATION_FRAME_LIMIT = 30');
    expect(main).toContain('desktopObservationFrames = desktopObservationFrames.slice(-DESKTOP_OBSERVATION_FRAME_LIMIT)');
    expect(main).toContain("type: 'desktop.observe.frame'");
    expect(main).toContain("error: 'desktop_observation_not_authorized'");
    expect(main).toContain("ipcMain.handle('shell-desktop-observation-frame'");
    expect(main).toContain('desktopObservationFrames = []');
    expect(preload).toContain('desktopObservationStart');
    expect(preload).toContain('desktopObservationFrame');
    expect(preload).toContain('desktopObservationStatus');
    expect(preload).toContain('desktopObservationStop');
    expect(html).not.toContain('data-shell-copilot-desktop-observation');
    expect(html).not.toContain('data-desktop-observation-scope="current_window"');
    expect(html).not.toContain('未授权时不采集');
    expect(panel).toContain('请求桌面观察授权');
    expect(panel).toContain('暂停桌面观察');
    expect(panel).toContain('停止桌面观察');
    expect(panel).toContain('function sanitizeTimelineText');
    expect(panel).toContain('function emitCopilotTimelineEvent');
    expect(panel).toContain('function renderCopilotTimeline');
    expect(panel).toContain('copilotTimelineEvents = copilotTimelineEvents.slice(-COPILOT_TIMELINE_LIMIT)');
    expect(panel).toContain("text.replace(/(token|cookie|secret|password|authorization)");
    expect(panel).toContain('[base64 redacted]');
    expect(panel).toContain('activeTask: buildActiveTaskState()');
    expect(panel).toContain('timeline: copilotTimelineEvents.slice(-COPILOT_TIMELINE_LIMIT)');
    expect(panel).toContain('renderShellCopilotPerceptionBar(runtimeState)');
    expect(panel).toContain("emitCopilotTimelineEvent({ source: 'user', title: '发送消息：' + text");
    expect(panel).toContain("emitCopilotTimelineEvent({ source: 'copilot', title: ev.message || '任务失败'");
    expect(panel).toContain("const perceptionEl = document.createElement('div')");
    expect(panel).toContain("'copilot-confirm-perception' + (perceptionSummary.stale ? ' is-stale' : '')");
    expect(panel).toContain('function canRememberLowRiskConfirm');
    expect(panel).toContain("ev.name === 'ac.workbench.run_capability'");
    expect(panel).toContain('function saveRememberedLowRiskTool');
    expect(panel).toContain('function revokeRememberedLowRiskTool');
    expect(panel).toContain('copilot-confirm-remember');
    expect(panel).toContain('允许并记住');
    expect(panel).toContain('已撤销低风险授权：');
    expect(panel).toContain('高风险仍会确认');
    expect(panel).toContain('上下文可能过期，请确认范围后再继续');
    expect(panel).toContain("title: approved ? (rememberLowRisk ? '已批准并记住低风险授权' : '已批准确认') : '已拒绝确认'");
    expect(panel).toContain("if (openOnFailure && timelineEl.open) timelineEl.open = true");
    expect(panel).toContain("activeTaskThreadCard.dataset.taskStatus = 'running'");
    expect(panel).toContain("activeTaskThreadCard.dataset.taskStatus = 'succeeded'");
    expect(panel).toContain("activeTaskThreadCard.dataset.taskStatus = 'failed'");
    expect(panel).toContain('summarizeShellExternalConnections');
    expect(panel).toContain('summarizeDesktopObservationState');
    expect(panel).toContain('formatPerceptionRefreshAge');
    expect(panel).toContain('lastPerceptionRefreshedAt');
    expect(panel).toContain('lastPerceptionRefreshFailed =');
    expect(panel).toContain('(!workbench && !external)');
    expect(panel).toContain('await refreshShellCopilotPerceptionBar()');
    expect(panel).toContain("} else if (ev.type === 'tool_status') {");
    expect(panel).toContain('loadProjectMemorySnapshot');
    expect(panel).toContain('saveProjectMemoryFromCopilot');
    expect(panel).toContain('summarizeWorkbenchContext');
    expect(panel).toContain('summarizeProjectMemorySnapshot');
    expect(panel).toContain('copilot-work-home');
    expect(panel).toContain('copilot-work-status-grid');
    expect(panel).toContain("\\u8d26\\u53f7");
    expect(panel).toContain("\\u5de5\\u4f5c\\u53f0");
    expect(panel).toContain('Agent');
    expect(panel).toContain("\\u6cbb\\u7406");
    expect(panel).toContain('startCopilotWorkTask');
    expect(panel).toContain('buildTaskThreadKey');
    expect(panel).toContain('setCurrentRunDock');
    expect(panel).toContain('noteCurrentRunActivity');
    expect(panel).toContain('clearCurrentRunDock');
    expect(panel).toContain('summarizeCopilotProductState');
    expect(panel).toContain('renderCopilotProductState');
    expect(panel).toContain("document.getElementById('copilot-top-state')");
    expect(panel).toContain("document.getElementById('copilot-context-title')");
    expect(panel).toContain("document.getElementById('copilot-current-run')");
    expect(panel).toContain('Prepare Workbench, create a new project');
    expect(panel).toContain('Read the current Workbench project context and list recent assets.');
    expect(panel).toContain('Use ac.workbench.ensure_ready with requireProject=true and createIfMissing=true');
    expect(panel).toContain('choose one directly runnable capability');
    expect(panel).toContain('runWorkbenchEntranceValidation(null');
    expect(panel).toContain('appendTaskThreadCard');
    expect(panel).toContain('const canReuse = activeTaskThreadCard && activeTaskThreadCard.isConnected && activeTaskThreadEls');
    expect(panel).toContain('const sameTask = canReuse && activeTaskThreadKey && activeTaskThreadKey === nextKey');
    expect(panel).toContain('card.dataset.taskId = nextKey ||');
    expect(panel).toContain('card.dataset.taskAttempt = String(sameTask ? activeTaskThreadAttempt + 1 : 1)');
    expect(panel).toContain("card.classList.remove('is-done', 'is-error')");
    expect(panel).toContain('appendResultCard');
    expect(panel).toContain('formatRecoveryDetail');
    expect(panel).toContain("kind: 'host-disconnected'");
    expect(panel).toContain('switchToConnections');
    expect(panel).toContain("'connections'");
    expect(panel).toContain('只生成方案');
    expect(panel).toContain('查看详情');
    expect(panel).toContain('if (!actions.contains(retryBtn)) actions.appendChild(retryBtn)');
    expect(panel).toContain('copilot-task-thread-card');
    expect(panel).toContain('copilot-task-thread-row is-attempt');
    expect(panel).toContain('copilot-result-card');
    expect(panel).toContain('AGENT_CREDITS_REQUIRED');
    expect(panel).toContain("kind: 'credits-required'");
    expect(panel).toContain('workbench_e2e_failed');
    expect(panel).toContain('is-save-outlet');
    expect(panel).toContain('updateActiveTaskThread');
    expect(panel).toContain('activeTaskThreadKey =');
    expect(panel).toContain('activeTaskThreadAttempt = 0');
    expect(panel).toContain("\\u4fdd\\u5b58\\u51fa\\u53e3");
    expect(panel).toContain("\\u9879\\u76ee\\u8bb0\\u5fc6");
    expect(panel).toContain("\\u8bb0\\u4f4f\\u7ed3\\u8bba");
    expect(panel).toContain("\\u8bb0\\u4f4f\\u53c2\\u6570");
    expect(panel).toContain("\\u8bb0\\u5f55\\u5f53\\u524d\\u72b6\\u6001");
    expect(panel).toContain("\\u6700\\u8fd1\\u4efb\\u52a1");

    expect(html).toContain('#shell-copilot .copilot-work-home');
    expect(html).toContain('#shell-copilot .copilot-msg.copilot-markdown');
    expect(html).toContain('#shell-copilot .copilot-code-block');
    expect(html).toContain('#shell-copilot .copilot-code-head');
    expect(html).toContain('#shell-copilot .copilot-code-copy');
    expect(html).toContain('#shell-copilot .copilot-inline-code');
    expect(html).not.toContain('id="copilot-perception-bar"');
    expect(html).not.toContain('data-shell-copilot-perception-bar');
    expect(html).not.toContain('id="copilot-perception-desktop"');
    expect(html).not.toContain('屏幕监控未开启');
    expect(html).not.toContain('id="copilot-timeline"');
    expect(html).not.toContain('data-shell-copilot-timeline');
    expect(html).not.toContain('id="copilot-desktop-observation"');
    expect(html).not.toContain('data-shell-copilot-desktop-observation');
    expect(html).not.toContain('data-desktop-observation-scope="current_window"');
    expect(html).toContain('#shell-copilot .copilot-perception-bar');
    expect(html).toContain('#shell-copilot .copilot-timeline');
    expect(html).toContain('#shell-copilot .copilot-timeline-event.is-failed');
    expect(html).toContain('#shell-copilot .copilot-confirm-perception');
    expect(html).toContain('#shell-copilot .copilot-confirm-perception.is-stale');
    expect(html).toContain('.copilot-policy-memory');
    expect(html).toContain('.copilot-confirm-remember');
    expect(html).toContain('#shell-copilot .copilot-desktop-observation');
    expect(html).toContain('#shell-copilot .copilot-desktop-scope-btn.is-active');
    expect(html).toContain('flex-wrap: wrap !important');
    expect(html).toContain('overflow-x: hidden !important');
    expect(html).toContain('max-height: none !important');
    expect(html).toContain('flex: 1 1 108px !important');
    expect(html).toContain('#shell-copilot .copilot-perception-chip.is-warn');
    expect(html).toContain('#shell-copilot .copilot-work-status-grid');
    expect(html).toContain('#shell-copilot .copilot-work-actions');
    expect(html).toContain('#shell-copilot .copilot-task-thread-card');
    expect(html).toContain('#shell-copilot .copilot-result-card');
    expect(html).toContain('#shell-copilot .copilot-recovery-detail');
    expect(html).not.toContain('id="copilot-current-run"');
    expect(html).not.toContain('id="copilot-top-state"');
    expect(html).not.toContain('id="copilot-context-title"');
    expect(html).toContain('copilot-design-alignment');
    expect(html).toContain('copilot-context-height-guard');
    expect(html).toContain('#shell-copilot .copilot-messages');
    expect(html).toContain('min-height: 180px !important');
    expect(html).toContain('#shell-copilot .copilot-timeline[open]');
    expect(html).toContain('#shell-copilot .copilot-context-head');
    expect(html).toContain('#shell-copilot .copilot-top-state');
    expect(html).toContain('#shell-copilot .copilot-current-run');

    expect(preload).toContain("workbenchContext: () => timedInvoke('agent-workbench-context'");
    expect(preload).toContain("projectMemory: (options) => timedInvoke('agent-project-memory-list'");
    expect(preload).toContain("saveProjectMemory: (entry) => timedInvoke('agent-project-memory-save'");
    expect(main).toContain('let agentWorkbenchClient = null');
    expect(main).toContain('agentWorkbenchClient = workbenchClient');
    expect(main).toContain("ipcMain.handle('agent-workbench-context'");
    expect(main).toContain("ipcMain.handle('agent-project-memory-list'");
    expect(main).toContain("ipcMain.handle('agent-project-memory-save'");
    expect(main).toContain('agentWorkbenchClient.getContext()');
    expect(main).toContain('agentStore.listToolExecutions({ limit: 5 })');
  });
});
