import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { basename, join, resolve } from 'node:path';
import { getRepositoryRoot } from '../repositoryVolume.js';

export const DEFAULT_CAVALRY_BRIDGE_PORT = 7431;
export const CAVALRY_BRIDGE_SCRIPT_NAME = 'assetcutter_cavalry_bridge.js';

export type CavalryBridgeTarget = {
  id: string;
  label: string;
  scriptsDir: string;
  scriptPath: string;
  hasScriptBridge: boolean;
};

export type CavalryBridgeInstallRecord = {
  port: number;
  installedAt: string;
  scriptsDirs: string[];
  targetIds: string[];
};

export type CavalryBridgeStatus = {
  id: 'cavalry';
  name: string;
  description: string;
  defaultPort: number;
  port: number;
  roots: string[];
  targets: CavalryBridgeTarget[];
  install: CavalryBridgeInstallRecord | null;
  installed: boolean;
  probe: { ok: boolean; message: string; heartbeatPath: string };
};

export type CavalryBridgeInstallBody = {
  targets?: string[];
  scriptsDirs?: string[];
  port?: number;
  home?: string;
};

function bridgesStateDir(): string {
  const sb = process.env.COMPANION_SANDBOX_ROOT?.trim();
  if (sb) return resolve(join(sb, 'bridges'));
  return resolve(join(getRepositoryRoot(), '..', 'bridges'));
}

function installRecordPath(): string {
  return join(bridgesStateDir(), 'cavalry-install.json');
}

function heartbeatPath(): string {
  const base =
    process.env.APPDATA ||
    process.env.LOCALAPPDATA ||
    process.env.TMP ||
    process.env.TEMP ||
    bridgesStateDir();
  return resolve(join(base, 'AssetCutterCompanion', 'bridges', 'cavalry-heartbeat.json'));
}

function normalizePort(raw: unknown): number {
  const n = Number(raw);
  return Number.isFinite(n) && n > 0 && n <= 65535 ? Math.floor(n) : DEFAULT_CAVALRY_BRIDGE_PORT;
}

function rootExists(path: string): boolean {
  try {
    return existsSync(path) && statSync(path).isDirectory();
  } catch {
    return false;
  }
}

export function discoverCavalryRoots(home = homedir()): string[] {
  const roots: string[] = [];
  const fromEnv = process.env.CAVALRY_SCRIPTS_DIR?.trim();
  if (fromEnv) roots.push(resolve(fromEnv));
  roots.push(resolve(join(home, 'Documents', 'Cavalry', 'Scripts')));
  roots.push(resolve(join(home, 'OneDrive', 'Documents', 'Cavalry', 'Scripts')));
  if (process.env.APPDATA) roots.push(resolve(join(process.env.APPDATA, 'Cavalry', 'Scripts')));
  return roots.filter((root, idx, arr) => (rootExists(root) || /Cavalry[\\/]Scripts$/i.test(root)) && arr.indexOf(root) === idx);
}

function targetFromScriptsDir(scriptsDir: string): CavalryBridgeTarget {
  const resolvedDir = resolve(scriptsDir);
  const parent = basename(resolve(join(resolvedDir, '..')));
  return {
    id: `cavalry::${resolvedDir}`,
    label: parent ? `Cavalry ${parent}` : 'Cavalry scripts',
    scriptsDir: resolvedDir,
    scriptPath: join(resolvedDir, CAVALRY_BRIDGE_SCRIPT_NAME),
    hasScriptBridge: existsSync(join(resolvedDir, CAVALRY_BRIDGE_SCRIPT_NAME)),
  };
}

export function discoverCavalryBridgeTargets(opts?: { home?: string; scriptsDirs?: string[] }): CavalryBridgeTarget[] {
  const byDir = new Map<string, CavalryBridgeTarget>();
  for (const root of discoverCavalryRoots(opts?.home)) byDir.set(resolve(root), targetFromScriptsDir(root));
  for (const dirRaw of opts?.scriptsDirs || []) {
    const dir = resolve(String(dirRaw || '').trim());
    if (dir) byDir.set(dir, targetFromScriptsDir(dir));
  }
  return Array.from(byDir.values()).sort((a, b) => a.scriptsDir.localeCompare(b.scriptsDir));
}

export function readCavalryBridgeInstallRecord(): CavalryBridgeInstallRecord | null {
  const p = installRecordPath();
  if (!existsSync(p)) return null;
  try {
    const raw = JSON.parse(readFileSync(p, 'utf8')) as CavalryBridgeInstallRecord;
    return {
      port: normalizePort(raw.port),
      installedAt: typeof raw.installedAt === 'string' ? raw.installedAt : '',
      scriptsDirs: Array.isArray(raw.scriptsDirs) ? raw.scriptsDirs.map(String) : [],
      targetIds: Array.isArray(raw.targetIds) ? raw.targetIds.map(String) : [],
    };
  } catch {
    return null;
  }
}

function writeCavalryBridgeInstallRecord(rec: CavalryBridgeInstallRecord): void {
  const dir = bridgesStateDir();
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const p = installRecordPath();
  const tmp = p + '.tmp';
  writeFileSync(tmp, JSON.stringify(rec, null, 2), 'utf8');
  renameSync(tmp, p);
}

function clearCavalryBridgeInstallRecord(): void {
  const p = installRecordPath();
  if (!existsSync(p)) return;
  try {
    unlinkSync(p);
  } catch {
    /* ignore */
  }
}

function jsString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function buildCavalryBridgeScript(port: number): string {
  const hb = heartbeatPath();
  return `// AssetCutter Cavalry Bridge
// Auto-generated by AssetCutter local companion.
var assetCutterHeartbeatPath = "${jsString(hb)}";
var assetCutterPort = ${port};

function assetCutterJsonEscape(value) {
  return String(value).replace(/\\\\/g, "\\\\\\\\").replace(/"/g, "\\\\\"");
}

function assetCutterHeartbeatPayload() {
  return '{"ok":true,"host":"cavalry","name":"Cavalry","port":' +
    String(assetCutterPort) +
    ',"at":"' +
    assetCutterJsonEscape(new Date().toISOString()) +
    '"}';
}

function assetCutterWriteHeartbeat() {
  try {
    if (typeof api !== "undefined" && api && typeof api.writeToFile === "function") {
      api.writeToFile(assetCutterHeartbeatPath, assetCutterHeartbeatPayload());
      return;
    }
    if (typeof cavalry !== "undefined" && cavalry && typeof cavalry.writeToFile === "function") {
      cavalry.writeToFile(assetCutterHeartbeatPath, assetCutterHeartbeatPayload());
      return;
    }
    if (typeof File !== "undefined") {
      var f = new File(assetCutterHeartbeatPath);
      f.open("w");
      f.write(assetCutterHeartbeatPayload());
      f.close();
    }
  } catch (e) {
    if (typeof console !== "undefined" && console.log) console.log(e);
  }
}

assetCutterWriteHeartbeat();
if (typeof setInterval === "function") setInterval(assetCutterWriteHeartbeat, 15000);
`;
}

async function probeCavalryBridge(): Promise<{ ok: boolean; message: string; heartbeatPath: string }> {
  const p = heartbeatPath();
  if (!existsSync(p)) return { ok: false, message: 'Cavalry bridge heartbeat has not been seen yet. Run the AssetCutter script from Cavalry Window > Scripts.', heartbeatPath: p };
  try {
    const stat = statSync(p);
    const ageMs = Date.now() - stat.mtimeMs;
    const json = JSON.parse(readFileSync(p, 'utf8')) as { host?: string };
    if (json.host !== 'cavalry') return { ok: false, message: 'Cavalry bridge heartbeat is invalid.', heartbeatPath: p };
    const mins = Math.max(0, Math.round(ageMs / 60000));
    return { ok: true, message: `Cavalry bridge heartbeat detected ${mins} min ago.`, heartbeatPath: p };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { ok: false, message: `Cavalry bridge heartbeat cannot be read: ${msg}`, heartbeatPath: p };
  }
}

export async function getCavalryBridgeStatus(opts?: { home?: string; scriptsDirs?: string[] }): Promise<CavalryBridgeStatus> {
  const targets = discoverCavalryBridgeTargets(opts);
  const install = readCavalryBridgeInstallRecord();
  const port = install?.port || DEFAULT_CAVALRY_BRIDGE_PORT;
  return {
    id: 'cavalry',
    name: 'Cavalry',
    description: 'One-click JavaScript UI Script bridge using a local heartbeat probe.',
    defaultPort: DEFAULT_CAVALRY_BRIDGE_PORT,
    port,
    roots: discoverCavalryRoots(opts?.home),
    targets,
    install,
    installed: targets.some((v) => v.hasScriptBridge) || Boolean(install?.scriptsDirs.length),
    probe: await probeCavalryBridge(),
  };
}

function resolveInstallTargets(
  body: CavalryBridgeInstallBody,
  discovered: CavalryBridgeTarget[],
): { targets: CavalryBridgeTarget[]; error?: string } {
  const byId = new Map(discovered.map((v) => [v.id, v]));
  const targets: CavalryBridgeTarget[] = [];
  for (const id of body.targets || []) {
    const v = byId.get(String(id));
    if (v) targets.push(v);
  }
  for (const dirRaw of body.scriptsDirs || []) {
    const scriptsDir = resolve(String(dirRaw || '').trim());
    if (scriptsDir) targets.push(targetFromScriptsDir(scriptsDir));
  }
  const unique = Array.from(new Map(targets.map((v) => [v.scriptsDir, v])).values());
  if (!unique.length) return { targets: [], error: 'no_cavalry_scripts_dir' };
  return { targets: unique };
}

export function installCavalryBridge(
  body: CavalryBridgeInstallBody = {},
):
  | { ok: true; port: number; installed: Array<{ targetId: string; scriptsDir: string; scriptPath: string }>; message: string }
  | { ok: false; error: string; message: string } {
  const port = normalizePort(body.port);
  const discovered = discoverCavalryBridgeTargets({ home: body.home, scriptsDirs: body.scriptsDirs });
  const resolved = resolveInstallTargets(body, discovered);
  if (resolved.error || !resolved.targets.length) {
    return {
      ok: false,
      error: resolved.error || 'no_cavalry_scripts_dir',
      message: 'No Cavalry Scripts folder was found. Choose the Cavalry Scripts folder manually.',
    };
  }
  const installed: Array<{ targetId: string; scriptsDir: string; scriptPath: string }> = [];
  for (const target of resolved.targets) {
    mkdirSync(target.scriptsDir, { recursive: true });
    writeFileSync(target.scriptPath, buildCavalryBridgeScript(port), 'utf8');
    installed.push({ targetId: target.id, scriptsDir: target.scriptsDir, scriptPath: target.scriptPath });
  }
  writeCavalryBridgeInstallRecord({
    port,
    installedAt: new Date().toISOString(),
    scriptsDirs: installed.map((x) => x.scriptsDir),
    targetIds: installed.map((x) => x.targetId),
  });
  return { ok: true, port, installed, message: 'Cavalry bridge installed. Run AssetCutter Cavalry Bridge from Cavalry Window > Scripts, then probe connection.' };
}

export function uninstallCavalryBridge(
  body: { targets?: string[]; scriptsDirs?: string[] } = {},
): { ok: true; removed: Array<{ scriptsDir: string; scriptPath: string }> } {
  const discovered = discoverCavalryBridgeTargets({ scriptsDirs: body.scriptsDirs });
  const record = readCavalryBridgeInstallRecord();
  const targets = new Map<string, CavalryBridgeTarget>();
  for (const v of discovered) {
    if (!body.targets || body.targets.length === 0 || body.targets.includes(v.id)) targets.set(v.scriptsDir, v);
  }
  for (const dir of record?.scriptsDirs || []) targets.set(resolve(dir), targetFromScriptsDir(dir));
  const removed: Array<{ scriptsDir: string; scriptPath: string }> = [];
  for (const target of targets.values()) {
    if (!existsSync(target.scriptPath)) continue;
    try {
      unlinkSync(target.scriptPath);
      removed.push({ scriptsDir: target.scriptsDir, scriptPath: target.scriptPath });
    } catch {
      /* ignore */
    }
  }
  clearCavalryBridgeInstallRecord();
  return { ok: true, removed };
}
