import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';
import { getRepositoryRoot } from '../repositoryVolume.js';

export const DEFAULT_FREECAD_BRIDGE_PORT = 7291;
export const FREECAD_WORKBENCH_NAME = 'AssetCutterBridge';
export const FREECAD_INIT_GUI_NAME = 'InitGui.py';

export type FreeCADBridgeTarget = {
  id: string;
  label: string;
  modDir: string;
  workbenchDir: string;
  initGuiPath: string;
  hasWorkbenchBridge: boolean;
};

export type FreeCADBridgeInstallRecord = {
  port: number;
  installedAt: string;
  modDirs: string[];
  targetIds: string[];
};

export type FreeCADBridgeStatus = {
  id: 'freecad';
  name: string;
  description: string;
  defaultPort: number;
  port: number;
  roots: string[];
  targets: FreeCADBridgeTarget[];
  install: FreeCADBridgeInstallRecord | null;
  installed: boolean;
  probe: { ok: boolean; message: string };
};

export type FreeCADBridgeInstallBody = {
  targets?: string[];
  modDirs?: string[];
  scriptsDirs?: string[];
  port?: number;
  home?: string;
};

function bridgesStateDir(): string {
  const sb = process.env.COMPANION_SANDBOX_ROOT?.trim();
  if (sb) return resolve(join(sb, 'bridges'));
  return resolve(join(getRepositoryRoot(), '..', 'bridges'));
}

function installRecordPath(): string {
  return join(bridgesStateDir(), 'freecad-install.json');
}

function normalizePort(raw: unknown): number {
  const n = Number(raw);
  return Number.isFinite(n) && n > 0 && n <= 65535 ? Math.floor(n) : DEFAULT_FREECAD_BRIDGE_PORT;
}

function rootExists(path: string): boolean {
  try {
    return existsSync(path) && statSync(path).isDirectory();
  } catch {
    return false;
  }
}

export function discoverFreeCADRoots(home = homedir()): string[] {
  const roots: string[] = [];
  const fromEnv = process.env.FREECAD_MOD_DIR?.trim();
  if (fromEnv) roots.push(resolve(fromEnv));
  if (process.env.APPDATA) roots.push(resolve(join(process.env.APPDATA, 'FreeCAD', 'Mod')));
  roots.push(resolve(join(home, 'AppData', 'Roaming', 'FreeCAD', 'Mod')));
  roots.push(resolve(join(home, '.local', 'share', 'FreeCAD', 'Mod')));
  roots.push(resolve(join(home, '.FreeCAD', 'Mod')));
  return roots.filter((root, idx, arr) => rootExists(root) && arr.indexOf(root) === idx);
}

function targetFromModDir(modDir: string): FreeCADBridgeTarget {
  const resolvedDir = resolve(modDir);
  const workbenchDir = join(resolvedDir, FREECAD_WORKBENCH_NAME);
  const initGuiPath = join(workbenchDir, FREECAD_INIT_GUI_NAME);
  return {
    id: `freecad::${resolvedDir}`,
    label: 'FreeCAD Mod folder',
    modDir: resolvedDir,
    workbenchDir,
    initGuiPath,
    hasWorkbenchBridge: existsSync(initGuiPath),
  };
}

export function discoverFreeCADBridgeTargets(opts?: { home?: string; modDirs?: string[]; scriptsDirs?: string[] }): FreeCADBridgeTarget[] {
  const byDir = new Map<string, FreeCADBridgeTarget>();
  for (const root of discoverFreeCADRoots(opts?.home)) byDir.set(resolve(root), targetFromModDir(root));
  for (const dirRaw of [...(opts?.modDirs || []), ...(opts?.scriptsDirs || [])]) {
    const dir = resolve(String(dirRaw || '').trim());
    if (dir) byDir.set(dir, targetFromModDir(dir));
  }
  return Array.from(byDir.values()).sort((a, b) => a.modDir.localeCompare(b.modDir));
}

export function readFreeCADBridgeInstallRecord(): FreeCADBridgeInstallRecord | null {
  const p = installRecordPath();
  if (!existsSync(p)) return null;
  try {
    const raw = JSON.parse(readFileSync(p, 'utf8')) as FreeCADBridgeInstallRecord;
    return {
      port: normalizePort(raw.port),
      installedAt: typeof raw.installedAt === 'string' ? raw.installedAt : '',
      modDirs: Array.isArray(raw.modDirs) ? raw.modDirs.map(String) : [],
      targetIds: Array.isArray(raw.targetIds) ? raw.targetIds.map(String) : [],
    };
  } catch {
    return null;
  }
}

function writeFreeCADBridgeInstallRecord(rec: FreeCADBridgeInstallRecord): void {
  const dir = bridgesStateDir();
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(installRecordPath(), JSON.stringify(rec, null, 2), 'utf8');
}

function clearFreeCADBridgeInstallRecord(): void {
  const p = installRecordPath();
  if (existsSync(p)) rmSync(p, { force: true });
}

function buildFreeCADInitGui(port: number): string {
  return `# AssetCutter FreeCAD Bridge
# Auto-generated by AssetCutter local companion.
import json
import threading
try:
    from http.server import BaseHTTPRequestHandler, HTTPServer
except Exception:
    from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer

PORT = ${port}
_server = None

class _AssetCutterFreeCADBridgeHandler(BaseHTTPRequestHandler):
    def log_message(self, *_args):
        return
    def _send(self, code, payload):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)
    def do_GET(self):
        if self.path.split("?", 1)[0] == "/health":
            self._send(200, {"ok": True, "host": "freecad"})
        else:
            self._send(404, {"ok": False, "error": "not_found"})

def _assetcutter_ensure_server():
    global _server
    if _server:
        return
    try:
        _server = HTTPServer(("127.0.0.1", PORT), _AssetCutterFreeCADBridgeHandler)
        threading.Thread(target=_server.serve_forever, daemon=True).start()
        print("[AssetCutter FreeCAD Bridge] ready on 127.0.0.1:%s" % PORT)
    except Exception as e:
        print("[AssetCutter FreeCAD Bridge] failed: %s" % e)

_assetcutter_ensure_server()
`;
}

async function probeFreeCADBridge(port: number, timeoutMs = 1800): Promise<{ ok: boolean; message: string }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(`http://127.0.0.1:${port}/health`, { signal: controller.signal });
    if (!res.ok) return { ok: false, message: `FreeCAD bridge returned HTTP ${res.status}` };
    const json = (await res.json().catch(() => null)) as { ok?: boolean } | null;
    return json && json.ok ? { ok: true, message: 'FreeCAD bridge connected' } : { ok: false, message: 'FreeCAD bridge response is invalid' };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { ok: false, message: `FreeCAD bridge is not reachable on 127.0.0.1:${port}: ${msg}` };
  } finally {
    clearTimeout(timer);
  }
}

export async function getFreeCADBridgeStatus(opts?: { home?: string; modDirs?: string[]; scriptsDirs?: string[] }): Promise<FreeCADBridgeStatus> {
  const targets = discoverFreeCADBridgeTargets(opts);
  const install = readFreeCADBridgeInstallRecord();
  const port = install?.port || DEFAULT_FREECAD_BRIDGE_PORT;
  return {
    id: 'freecad',
    name: 'FreeCAD',
    description: 'One-click Workbench bridge using InitGui.py and a local HTTP probe.',
    defaultPort: DEFAULT_FREECAD_BRIDGE_PORT,
    port,
    roots: discoverFreeCADRoots(opts?.home),
    targets,
    install,
    installed: targets.some((v) => v.hasWorkbenchBridge) || Boolean(install?.modDirs.length),
    probe: await probeFreeCADBridge(port),
  };
}

function resolveInstallTargets(
  body: FreeCADBridgeInstallBody,
  discovered: FreeCADBridgeTarget[],
): { targets: FreeCADBridgeTarget[]; error?: string } {
  const byId = new Map(discovered.map((v) => [v.id, v]));
  const targets: FreeCADBridgeTarget[] = [];
  for (const id of body.targets || []) {
    const v = byId.get(String(id));
    if (v) targets.push(v);
  }
  for (const dirRaw of [...(body.modDirs || []), ...(body.scriptsDirs || [])]) {
    const modDir = resolve(String(dirRaw || '').trim());
    if (modDir) targets.push(targetFromModDir(modDir));
  }
  const unique = Array.from(new Map(targets.map((v) => [v.modDir, v])).values());
  if (!unique.length) return { targets: [], error: 'no_freecad_mod_dir' };
  return { targets: unique };
}

export function installFreeCADBridge(
  body: FreeCADBridgeInstallBody = {},
):
  | { ok: true; port: number; installed: Array<{ targetId: string; modDir: string; workbenchDir: string; initGuiPath: string }>; message: string }
  | { ok: false; error: string; message: string } {
  const port = normalizePort(body.port);
  const discovered = discoverFreeCADBridgeTargets({ home: body.home, modDirs: body.modDirs, scriptsDirs: body.scriptsDirs });
  const resolved = resolveInstallTargets(body, discovered);
  if (resolved.error || !resolved.targets.length) {
    return { ok: false, error: resolved.error || 'no_freecad_mod_dir', message: 'No FreeCAD Mod folder was found. Choose the Mod folder manually.' };
  }
  const installed: Array<{ targetId: string; modDir: string; workbenchDir: string; initGuiPath: string }> = [];
  for (const target of resolved.targets) {
    mkdirSync(target.workbenchDir, { recursive: true });
    writeFileSync(target.initGuiPath, buildFreeCADInitGui(port), 'utf8');
    installed.push({ targetId: target.id, modDir: target.modDir, workbenchDir: target.workbenchDir, initGuiPath: target.initGuiPath });
  }
  writeFreeCADBridgeInstallRecord({
    port,
    installedAt: new Date().toISOString(),
    modDirs: installed.map((x) => x.modDir),
    targetIds: installed.map((x) => x.targetId),
  });
  return { ok: true, port, installed, message: 'FreeCAD bridge installed. Restart FreeCAD, then probe connection.' };
}

export function uninstallFreeCADBridge(
  body: { targets?: string[]; modDirs?: string[]; scriptsDirs?: string[] } = {},
): { ok: true; removed: Array<{ modDir: string; workbenchDir: string; removed: boolean }> } {
  const discovered = discoverFreeCADBridgeTargets({ modDirs: body.modDirs, scriptsDirs: body.scriptsDirs });
  const record = readFreeCADBridgeInstallRecord();
  const targets = new Map<string, FreeCADBridgeTarget>();
  for (const v of discovered) {
    if (!body.targets || body.targets.length === 0 || body.targets.includes(v.id)) targets.set(v.modDir, v);
  }
  for (const dir of record?.modDirs || []) targets.set(resolve(dir), targetFromModDir(dir));
  const removed: Array<{ modDir: string; workbenchDir: string; removed: boolean }> = [];
  for (const target of targets.values()) {
    try {
      if (existsSync(target.workbenchDir)) rmSync(target.workbenchDir, { recursive: true, force: true });
      removed.push({ modDir: target.modDir, workbenchDir: target.workbenchDir, removed: true });
    } catch {
      removed.push({ modDir: target.modDir, workbenchDir: target.workbenchDir, removed: false });
    }
  }
  clearFreeCADBridgeInstallRecord();
  return { ok: true, removed };
}
