import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';
import { getRepositoryRoot } from '../repositoryVolume.js';

export const DEFAULT_GIMP_BRIDGE_PORT = 7251;
export const GIMP_BRIDGE_PLUGIN_NAME = 'assetcutter_gimp_bridge.py';

export type GimpBridgeTarget = {
  id: string;
  label: string;
  pluginDir: string;
  scriptsDir: string;
  pluginPath: string;
  hasScriptBridge: boolean;
};

export type GimpBridgeInstallRecord = {
  port: number;
  installedAt: string;
  pluginDirs: string[];
  targetIds: string[];
};

export type GimpBridgeStatus = {
  id: 'gimp';
  name: string;
  description: string;
  defaultPort: number;
  port: number;
  roots: string[];
  targets: GimpBridgeTarget[];
  install: GimpBridgeInstallRecord | null;
  installed: boolean;
  probe: { ok: boolean; message: string };
};

export type GimpBridgeInstallBody = {
  targets?: string[];
  pluginDirs?: string[];
  scriptsDirs?: string[];
  port?: number;
  home?: string;
};

function bridgesStateDir(): string {
  const sb = process.env.COMPANION_SANDBOX_ROOT?.trim();
  if (sb) return resolve(join(sb, 'bridges'));
  return resolve(join(getRepositoryRoot(), '..', 'bridges'));
}

function installRecordPath(): string {
  return join(bridgesStateDir(), 'gimp-install.json');
}

function normalizePort(raw: unknown): number {
  const n = Number(raw);
  return Number.isFinite(n) && n > 0 && n <= 65535 ? Math.floor(n) : DEFAULT_GIMP_BRIDGE_PORT;
}

function rootExists(path: string): boolean {
  try {
    return existsSync(path) && statSync(path).isDirectory();
  } catch {
    return false;
  }
}

export function discoverGimpRoots(home = homedir()): string[] {
  const roots: string[] = [];
  const fromEnv = process.env.GIMP_PLUGIN_DIR?.trim();
  if (fromEnv) roots.push(resolve(fromEnv));
  if (process.env.APPDATA) {
    roots.push(resolve(join(process.env.APPDATA, 'GIMP', '2.10', 'plug-ins')));
    roots.push(resolve(join(process.env.APPDATA, 'GIMP', '3.0', 'plug-ins')));
  }
  roots.push(resolve(join(home, 'AppData', 'Roaming', 'GIMP', '2.10', 'plug-ins')));
  roots.push(resolve(join(home, 'AppData', 'Roaming', 'GIMP', '3.0', 'plug-ins')));
  roots.push(resolve(join(home, '.config', 'GIMP', '2.10', 'plug-ins')));
  roots.push(resolve(join(home, '.config', 'GIMP', '3.0', 'plug-ins')));
  return roots.filter((root, idx, arr) => rootExists(root) && arr.indexOf(root) === idx);
}

function targetFromPluginDir(pluginDir: string): GimpBridgeTarget {
  const resolvedDir = resolve(pluginDir);
  const pluginPath = join(resolvedDir, GIMP_BRIDGE_PLUGIN_NAME);
  return {
    id: `gimp::${resolvedDir}`,
    label: 'GIMP plug-ins',
    pluginDir: resolvedDir,
    scriptsDir: resolvedDir,
    pluginPath,
    hasScriptBridge: existsSync(pluginPath),
  };
}

export function discoverGimpBridgeTargets(opts?: { home?: string; pluginDirs?: string[]; scriptsDirs?: string[] }): GimpBridgeTarget[] {
  const byDir = new Map<string, GimpBridgeTarget>();
  for (const root of discoverGimpRoots(opts?.home)) byDir.set(resolve(root), targetFromPluginDir(root));
  for (const dirRaw of [...(opts?.pluginDirs || []), ...(opts?.scriptsDirs || [])]) {
    const dir = resolve(String(dirRaw || '').trim());
    if (dir) byDir.set(dir, targetFromPluginDir(dir));
  }
  return Array.from(byDir.values()).sort((a, b) => a.pluginDir.localeCompare(b.pluginDir));
}

export function readGimpBridgeInstallRecord(): GimpBridgeInstallRecord | null {
  const p = installRecordPath();
  if (!existsSync(p)) return null;
  try {
    const raw = JSON.parse(readFileSync(p, 'utf8')) as GimpBridgeInstallRecord;
    return {
      port: normalizePort(raw.port),
      installedAt: typeof raw.installedAt === 'string' ? raw.installedAt : '',
      pluginDirs: Array.isArray(raw.pluginDirs) ? raw.pluginDirs.map(String) : [],
      targetIds: Array.isArray(raw.targetIds) ? raw.targetIds.map(String) : [],
    };
  } catch {
    return null;
  }
}

function writeGimpBridgeInstallRecord(rec: GimpBridgeInstallRecord): void {
  const dir = bridgesStateDir();
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const p = installRecordPath();
  const tmp = p + '.tmp';
  writeFileSync(tmp, JSON.stringify(rec, null, 2), 'utf8');
  renameSync(tmp, p);
}

function clearGimpBridgeInstallRecord(): void {
  const p = installRecordPath();
  if (!existsSync(p)) return;
  try {
    unlinkSync(p);
  } catch {
    /* ignore */
  }
}

function buildGimpBridgeScript(port: number): string {
  return `#!/usr/bin/env python
# AssetCutter GIMP Bridge
# Auto-generated by AssetCutter local companion.
import json
import threading
try:
    from http.server import BaseHTTPRequestHandler, HTTPServer
except Exception:
    from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer

try:
    from gimpfu import *
except Exception:
    register = None
    main = None
    PF_IMAGE = 0
    PF_DRAWABLE = 0

PORT = ${port}
_server = None

class Handler(BaseHTTPRequestHandler):
    def log_message(self, *_args):
        return
    def _send(self, code, payload):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)
    def do_GET(self):
        if self.path.split("?", 1)[0] == "/health":
            self._send(200, {"ok": True, "host": "gimp"})
        else:
            self._send(404, {"ok": False, "error": "not_found"})

def ensure_server():
    global _server
    if _server:
        return
    try:
        _server = HTTPServer(("127.0.0.1", PORT), Handler)
        threading.Thread(target=_server.serve_forever, daemon=True).start()
        print("[AssetCutter GIMP Bridge] ready on 127.0.0.1:%s" % PORT)
    except Exception as e:
        print("[AssetCutter GIMP Bridge] failed: %s" % e)

def assetcutter_gimp_bridge(image=None, drawable=None):
    ensure_server()

ensure_server()

if register is not None:
    register(
        "python_fu_assetcutter_bridge",
        "AssetCutter Bridge",
        "Starts the AssetCutter local bridge health endpoint.",
        "AssetCutter",
        "AssetCutter",
        "2026",
        "AssetCutter Bridge",
        "*",
        [
            (PF_IMAGE, "image", "Input image", None),
            (PF_DRAWABLE, "drawable", "Input drawable", None),
        ],
        [],
        assetcutter_gimp_bridge,
        menu="<Image>/Filters/AssetCutter",
    )
    main()
`;
}

async function probeGimpBridge(port: number, timeoutMs = 1800): Promise<{ ok: boolean; message: string }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(`http://127.0.0.1:${port}/health`, { signal: controller.signal });
    if (!res.ok) return { ok: false, message: `GIMP bridge returned HTTP ${res.status}` };
    const json = (await res.json().catch(() => null)) as { ok?: boolean } | null;
    return json && json.ok ? { ok: true, message: 'GIMP bridge connected' } : { ok: false, message: 'GIMP bridge response is invalid' };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { ok: false, message: `GIMP bridge is not reachable on 127.0.0.1:${port}: ${msg}` };
  } finally {
    clearTimeout(timer);
  }
}

export async function getGimpBridgeStatus(opts?: { home?: string; pluginDirs?: string[]; scriptsDirs?: string[] }): Promise<GimpBridgeStatus> {
  const targets = discoverGimpBridgeTargets(opts);
  const install = readGimpBridgeInstallRecord();
  const port = install?.port || DEFAULT_GIMP_BRIDGE_PORT;
  return {
    id: 'gimp',
    name: 'GIMP',
    description: 'One-click Python-Fu plugin bridge using a local HTTP probe.',
    defaultPort: DEFAULT_GIMP_BRIDGE_PORT,
    port,
    roots: discoverGimpRoots(opts?.home),
    targets,
    install,
    installed: targets.some((v) => v.hasScriptBridge) || Boolean(install?.pluginDirs.length),
    probe: await probeGimpBridge(port),
  };
}

function resolveInstallTargets(
  body: GimpBridgeInstallBody,
  discovered: GimpBridgeTarget[],
): { targets: GimpBridgeTarget[]; error?: string } {
  const byId = new Map(discovered.map((v) => [v.id, v]));
  const targets: GimpBridgeTarget[] = [];
  for (const id of body.targets || []) {
    const v = byId.get(String(id));
    if (v) targets.push(v);
  }
  for (const dirRaw of [...(body.pluginDirs || []), ...(body.scriptsDirs || [])]) {
    const pluginDir = resolve(String(dirRaw || '').trim());
    if (pluginDir) targets.push(targetFromPluginDir(pluginDir));
  }
  const unique = Array.from(new Map(targets.map((v) => [v.pluginDir, v])).values());
  if (!unique.length) return { targets: [], error: 'no_gimp_plugin_dir' };
  return { targets: unique };
}

export function installGimpBridge(
  body: GimpBridgeInstallBody = {},
):
  | { ok: true; port: number; installed: Array<{ targetId: string; pluginDir: string; pluginPath: string }>; message: string }
  | { ok: false; error: string; message: string } {
  const port = normalizePort(body.port);
  const discovered = discoverGimpBridgeTargets({ home: body.home, pluginDirs: body.pluginDirs, scriptsDirs: body.scriptsDirs });
  const resolved = resolveInstallTargets(body, discovered);
  if (resolved.error || !resolved.targets.length) {
    return { ok: false, error: resolved.error || 'no_gimp_plugin_dir', message: 'No GIMP plug-ins folder was found. Choose the plug-ins folder manually.' };
  }
  const installed: Array<{ targetId: string; pluginDir: string; pluginPath: string }> = [];
  for (const target of resolved.targets) {
    mkdirSync(target.pluginDir, { recursive: true });
    writeFileSync(target.pluginPath, buildGimpBridgeScript(port), 'utf8');
    try {
      chmodSync(target.pluginPath, 0o755);
    } catch {
      /* ignore */
    }
    installed.push({ targetId: target.id, pluginDir: target.pluginDir, pluginPath: target.pluginPath });
  }
  writeGimpBridgeInstallRecord({
    port,
    installedAt: new Date().toISOString(),
    pluginDirs: installed.map((x) => x.pluginDir),
    targetIds: installed.map((x) => x.targetId),
  });
  return { ok: true, port, installed, message: 'GIMP bridge installed. Restart GIMP and run Filters > AssetCutter > AssetCutter Bridge, then probe connection.' };
}

export function uninstallGimpBridge(
  body: { targets?: string[]; pluginDirs?: string[]; scriptsDirs?: string[] } = {},
): { ok: true; removed: Array<{ pluginDir: string; pluginPath: string }> } {
  const discovered = discoverGimpBridgeTargets({ pluginDirs: body.pluginDirs, scriptsDirs: body.scriptsDirs });
  const record = readGimpBridgeInstallRecord();
  const targets = new Map<string, GimpBridgeTarget>();
  for (const v of discovered) {
    if (!body.targets || body.targets.length === 0 || body.targets.includes(v.id)) targets.set(v.pluginDir, v);
  }
  for (const dir of record?.pluginDirs || []) targets.set(resolve(dir), targetFromPluginDir(dir));
  const removed: Array<{ pluginDir: string; pluginPath: string }> = [];
  for (const target of targets.values()) {
    try {
      if (existsSync(target.pluginPath)) unlinkSync(target.pluginPath);
      removed.push({ pluginDir: target.pluginDir, pluginPath: target.pluginPath });
    } catch {
      /* ignore */
    }
  }
  clearGimpBridgeInstallRecord();
  return { ok: true, removed };
}
