import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';
import { getRepositoryRoot } from '../repositoryVolume.js';

export const DEFAULT_METASHAPE_BRIDGE_PORT = 7541;
export const METASHAPE_BRIDGE_SCRIPT_NAME = 'assetcutter_metashape_bridge.py';

export type MetashapeBridgeTarget = {
  id: string;
  label: string;
  scriptsDir: string;
  scriptPath: string;
  hasScriptBridge: boolean;
};

export type MetashapeBridgeInstallRecord = {
  port: number;
  installedAt: string;
  scriptsDirs: string[];
  targetIds: string[];
};

export type MetashapeBridgeStatus = {
  id: 'metashape';
  name: string;
  description: string;
  defaultPort: number;
  port: number;
  roots: string[];
  targets: MetashapeBridgeTarget[];
  install: MetashapeBridgeInstallRecord | null;
  installed: boolean;
  probe: { ok: boolean; message: string; heartbeatPath: string };
};

export type MetashapeBridgeInstallBody = {
  targets?: string[];
  scriptsDirs?: string[];
  port?: number;
  home?: string;
};

function bridgesStateDir(): string {
  const sb = process.env.COMPANION_SANDBOX_ROOT?.trim();
  if (sb) return resolve(join(sb, 'bridges'));
  return resolve(join(getRepositoryRoot(), '..', 'bridges'));
}

function installRecordPath(): string {
  return join(bridgesStateDir(), 'metashape-install.json');
}

function heartbeatPath(): string {
  const base =
    process.env.APPDATA ||
    process.env.LOCALAPPDATA ||
    process.env.TMP ||
    process.env.TEMP ||
    bridgesStateDir();
  return resolve(join(base, 'AssetCutterCompanion', 'bridges', 'metashape-heartbeat.json'));
}

function normalizePort(raw: unknown): number {
  const n = Number(raw);
  return Number.isFinite(n) && n > 0 && n <= 65535 ? Math.floor(n) : DEFAULT_METASHAPE_BRIDGE_PORT;
}

function rootExists(path: string): boolean {
  try {
    return existsSync(path) && statSync(path).isDirectory();
  } catch {
    return false;
  }
}

export function discoverMetashapeRoots(home = homedir()): string[] {
  const roots: string[] = [];
  const fromEnv = process.env.METASHAPE_SCRIPTS_DIR?.trim();
  if (fromEnv) roots.push(resolve(fromEnv));
  if (process.env.LOCALAPPDATA) roots.push(resolve(join(process.env.LOCALAPPDATA, 'Agisoft', 'Metashape Pro', 'scripts')));
  roots.push(resolve(join(home, 'AppData', 'Local', 'Agisoft', 'Metashape Pro', 'scripts')));
  return roots.filter((root, idx, arr) => (rootExists(root) || /[\\/]Agisoft[\\/]Metashape Pro[\\/]scripts$/i.test(root)) && arr.indexOf(root) === idx);
}

function targetFromScriptsDir(scriptsDir: string): MetashapeBridgeTarget {
  const resolvedDir = resolve(scriptsDir);
  return {
    id: `metashape::${resolvedDir}`,
    label: 'Metashape Pro scripts',
    scriptsDir: resolvedDir,
    scriptPath: join(resolvedDir, METASHAPE_BRIDGE_SCRIPT_NAME),
    hasScriptBridge: existsSync(join(resolvedDir, METASHAPE_BRIDGE_SCRIPT_NAME)),
  };
}

export function discoverMetashapeBridgeTargets(opts?: { home?: string; scriptsDirs?: string[] }): MetashapeBridgeTarget[] {
  const byDir = new Map<string, MetashapeBridgeTarget>();
  for (const root of discoverMetashapeRoots(opts?.home)) byDir.set(resolve(root), targetFromScriptsDir(root));
  for (const dirRaw of opts?.scriptsDirs || []) {
    const dir = resolve(String(dirRaw || '').trim());
    if (dir) byDir.set(dir, targetFromScriptsDir(dir));
  }
  return Array.from(byDir.values()).sort((a, b) => a.scriptsDir.localeCompare(b.scriptsDir));
}

export function readMetashapeBridgeInstallRecord(): MetashapeBridgeInstallRecord | null {
  const p = installRecordPath();
  if (!existsSync(p)) return null;
  try {
    const raw = JSON.parse(readFileSync(p, 'utf8')) as MetashapeBridgeInstallRecord;
    return {
      port: normalizePort(raw.port),
      installedAt: typeof raw.installedAt === 'string' ? raw.installedAt : '',
      scriptsDirs: Array.isArray(raw.scriptsDirs) ? raw.scriptsDirs.map(String) : [],
      targetIds: Array.isArray(raw.targetIds) ? raw.targetIds.map(String) : [],
    };
  } catch {
    return null;
  }
}

function writeMetashapeBridgeInstallRecord(rec: MetashapeBridgeInstallRecord): void {
  const dir = bridgesStateDir();
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const p = installRecordPath();
  const tmp = p + '.tmp';
  writeFileSync(tmp, JSON.stringify(rec, null, 2), 'utf8');
  renameSync(tmp, p);
}

function clearMetashapeBridgeInstallRecord(): void {
  const p = installRecordPath();
  if (!existsSync(p)) return;
  try {
    unlinkSync(p);
  } catch {
    /* ignore */
  }
}

function pyString(s: string): string {
  return JSON.stringify(s);
}

function buildMetashapeBridgeScript(port: number): string {
  const hb = heartbeatPath();
  return `# AssetCutter Metashape Bridge
# Auto-generated by AssetCutter local companion.
import datetime
import json
import os

HEARTBEAT_PATH = ${pyString(hb)}
PORT = ${port}

def assetcutter_write_heartbeat():
    folder = os.path.dirname(HEARTBEAT_PATH)
    if folder and not os.path.isdir(folder):
        os.makedirs(folder, exist_ok=True)
    payload = {
        "ok": True,
        "host": "metashape",
        "name": "Metashape",
        "port": PORT,
        "at": datetime.datetime.utcnow().isoformat() + "Z",
    }
    with open(HEARTBEAT_PATH, "w", encoding="utf-8") as f:
        json.dump(payload, f)

assetcutter_write_heartbeat()

try:
    import Metashape
except Exception:
    Metashape = None

if Metashape is not None:
    try:
        Metashape.app.addMenuItem("AssetCutter/Refresh Bridge", assetcutter_write_heartbeat)
    except Exception:
        pass
`;
}

async function probeMetashapeBridge(): Promise<{ ok: boolean; message: string; heartbeatPath: string }> {
  const p = heartbeatPath();
  if (!existsSync(p)) return { ok: false, message: 'Metashape bridge heartbeat has not been seen yet. Restart Metashape Pro or run AssetCutter/Refresh Bridge.', heartbeatPath: p };
  try {
    const stat = statSync(p);
    const ageMs = Date.now() - stat.mtimeMs;
    const json = JSON.parse(readFileSync(p, 'utf8')) as { host?: string };
    if (json.host !== 'metashape') return { ok: false, message: 'Metashape bridge heartbeat is invalid.', heartbeatPath: p };
    const mins = Math.max(0, Math.round(ageMs / 60000));
    return { ok: true, message: `Metashape bridge heartbeat detected ${mins} min ago.`, heartbeatPath: p };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { ok: false, message: `Metashape bridge heartbeat cannot be read: ${msg}`, heartbeatPath: p };
  }
}

export async function getMetashapeBridgeStatus(opts?: { home?: string; scriptsDirs?: string[] }): Promise<MetashapeBridgeStatus> {
  const targets = discoverMetashapeBridgeTargets(opts);
  const install = readMetashapeBridgeInstallRecord();
  const port = install?.port || DEFAULT_METASHAPE_BRIDGE_PORT;
  return {
    id: 'metashape',
    name: 'Metashape',
    description: 'One-click Metashape autorun Python bridge using a local heartbeat probe.',
    defaultPort: DEFAULT_METASHAPE_BRIDGE_PORT,
    port,
    roots: discoverMetashapeRoots(opts?.home),
    targets,
    install,
    installed: targets.some((v) => v.hasScriptBridge) || Boolean(install?.scriptsDirs.length),
    probe: await probeMetashapeBridge(),
  };
}

function resolveInstallTargets(
  body: MetashapeBridgeInstallBody,
  discovered: MetashapeBridgeTarget[],
): { targets: MetashapeBridgeTarget[]; error?: string } {
  const byId = new Map(discovered.map((v) => [v.id, v]));
  const targets: MetashapeBridgeTarget[] = [];
  for (const id of body.targets || []) {
    const v = byId.get(String(id));
    if (v) targets.push(v);
  }
  for (const dirRaw of body.scriptsDirs || []) {
    const scriptsDir = resolve(String(dirRaw || '').trim());
    if (scriptsDir) targets.push(targetFromScriptsDir(scriptsDir));
  }
  const unique = Array.from(new Map(targets.map((v) => [v.scriptsDir, v])).values());
  if (!unique.length) return { targets: [], error: 'no_metashape_scripts_dir' };
  return { targets: unique };
}

export function installMetashapeBridge(
  body: MetashapeBridgeInstallBody = {},
):
  | { ok: true; port: number; installed: Array<{ targetId: string; scriptsDir: string; scriptPath: string }>; message: string }
  | { ok: false; error: string; message: string } {
  const port = normalizePort(body.port);
  const discovered = discoverMetashapeBridgeTargets({ home: body.home, scriptsDirs: body.scriptsDirs });
  const resolved = resolveInstallTargets(body, discovered);
  if (resolved.error || !resolved.targets.length) {
    return {
      ok: false,
      error: resolved.error || 'no_metashape_scripts_dir',
      message: 'No Metashape Pro scripts folder was found. Choose the scripts folder manually.',
    };
  }
  const installed: Array<{ targetId: string; scriptsDir: string; scriptPath: string }> = [];
  for (const target of resolved.targets) {
    mkdirSync(target.scriptsDir, { recursive: true });
    writeFileSync(target.scriptPath, buildMetashapeBridgeScript(port), 'utf8');
    installed.push({ targetId: target.id, scriptsDir: target.scriptsDir, scriptPath: target.scriptPath });
  }
  writeMetashapeBridgeInstallRecord({
    port,
    installedAt: new Date().toISOString(),
    scriptsDirs: installed.map((x) => x.scriptsDir),
    targetIds: installed.map((x) => x.targetId),
  });
  return { ok: true, port, installed, message: 'Metashape bridge installed. Restart Metashape Pro, then probe connection.' };
}

export function uninstallMetashapeBridge(
  body: { targets?: string[]; scriptsDirs?: string[] } = {},
): { ok: true; removed: Array<{ scriptsDir: string; scriptPath: string }> } {
  const discovered = discoverMetashapeBridgeTargets({ scriptsDirs: body.scriptsDirs });
  const record = readMetashapeBridgeInstallRecord();
  const targets = new Map<string, MetashapeBridgeTarget>();
  for (const v of discovered) {
    if (!body.targets || body.targets.length === 0 || body.targets.includes(v.id)) targets.set(v.scriptsDir, v);
  }
  for (const dir of record?.scriptsDirs || []) targets.set(resolve(dir), targetFromScriptsDir(dir));
  const removed: Array<{ scriptsDir: string; scriptPath: string }> = [];
  for (const target of targets.values()) {
    if (!existsSync(target.scriptPath)) continue;
    try {
      unlinkSync(target.scriptPath);
      removed.push({ scriptsDir: target.scriptsDir, scriptPath: target.scriptPath });
    } catch {
      /* ignore */
    }
  }
  clearMetashapeBridgeInstallRecord();
  return { ok: true, removed };
}
