import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { basename, join, resolve } from 'node:path';
import { getRepositoryRoot } from '../repositoryVolume.js';

export const DEFAULT_RIZOMUV_BRIDGE_PORT = 7461;
export const RIZOMUV_BRIDGE_SCRIPT_NAME = 'assetcutter_rizomuv_bridge.lua';

export type RizomUvBridgeTarget = {
  id: string;
  label: string;
  scriptsDir: string;
  scriptPath: string;
  hasScriptBridge: boolean;
};

export type RizomUvBridgeInstallRecord = {
  port: number;
  installedAt: string;
  scriptsDirs: string[];
  targetIds: string[];
};

export type RizomUvBridgeStatus = {
  id: 'rizomuv';
  name: string;
  description: string;
  defaultPort: number;
  port: number;
  roots: string[];
  targets: RizomUvBridgeTarget[];
  install: RizomUvBridgeInstallRecord | null;
  installed: boolean;
  probe: { ok: boolean; message: string; heartbeatPath: string };
};

export type RizomUvBridgeInstallBody = {
  targets?: string[];
  scriptsDirs?: string[];
  port?: number;
  home?: string;
};

function bridgesStateDir(): string {
  const sb = process.env.COMPANION_SANDBOX_ROOT?.trim();
  if (sb) return resolve(join(sb, 'bridges'));
  return resolve(join(getRepositoryRoot(), '..', 'bridges'));
}

function installRecordPath(): string {
  return join(bridgesStateDir(), 'rizomuv-install.json');
}

function heartbeatPath(): string {
  const base =
    process.env.APPDATA ||
    process.env.LOCALAPPDATA ||
    process.env.TMP ||
    process.env.TEMP ||
    bridgesStateDir();
  return resolve(join(base, 'AssetCutterCompanion', 'bridges', 'rizomuv-heartbeat.json'));
}

function normalizePort(raw: unknown): number {
  const n = Number(raw);
  return Number.isFinite(n) && n > 0 && n <= 65535 ? Math.floor(n) : DEFAULT_RIZOMUV_BRIDGE_PORT;
}

function rootExists(path: string): boolean {
  try {
    return existsSync(path) && statSync(path).isDirectory();
  } catch {
    return false;
  }
}

export function discoverRizomUvRoots(home = homedir()): string[] {
  const roots: string[] = [];
  const fromEnv = process.env.RIZOMUV_SCRIPTS_DIR?.trim();
  if (fromEnv) roots.push(resolve(fromEnv));
  roots.push(resolve(join(home, 'Documents', 'RizomUV', 'Scripts')));
  roots.push(resolve(join(home, 'OneDrive', 'Documents', 'RizomUV', 'Scripts')));
  if (process.env.APPDATA) roots.push(resolve(join(process.env.APPDATA, 'RizomUV', 'Scripts')));
  return roots.filter((root, idx, arr) => (rootExists(root) || /RizomUV[\\/]Scripts$/i.test(root)) && arr.indexOf(root) === idx);
}

function targetFromScriptsDir(scriptsDir: string): RizomUvBridgeTarget {
  const resolvedDir = resolve(scriptsDir);
  const parent = basename(resolve(join(resolvedDir, '..')));
  return {
    id: `rizomuv::${resolvedDir}`,
    label: parent ? `RizomUV ${parent}` : 'RizomUV scripts',
    scriptsDir: resolvedDir,
    scriptPath: join(resolvedDir, RIZOMUV_BRIDGE_SCRIPT_NAME),
    hasScriptBridge: existsSync(join(resolvedDir, RIZOMUV_BRIDGE_SCRIPT_NAME)),
  };
}

export function discoverRizomUvBridgeTargets(opts?: { home?: string; scriptsDirs?: string[] }): RizomUvBridgeTarget[] {
  const byDir = new Map<string, RizomUvBridgeTarget>();
  for (const root of discoverRizomUvRoots(opts?.home)) byDir.set(resolve(root), targetFromScriptsDir(root));
  for (const dirRaw of opts?.scriptsDirs || []) {
    const dir = resolve(String(dirRaw || '').trim());
    if (dir) byDir.set(dir, targetFromScriptsDir(dir));
  }
  return Array.from(byDir.values()).sort((a, b) => a.scriptsDir.localeCompare(b.scriptsDir));
}

export function readRizomUvBridgeInstallRecord(): RizomUvBridgeInstallRecord | null {
  const p = installRecordPath();
  if (!existsSync(p)) return null;
  try {
    const raw = JSON.parse(readFileSync(p, 'utf8')) as RizomUvBridgeInstallRecord;
    return {
      port: normalizePort(raw.port),
      installedAt: typeof raw.installedAt === 'string' ? raw.installedAt : '',
      scriptsDirs: Array.isArray(raw.scriptsDirs) ? raw.scriptsDirs.map(String) : [],
      targetIds: Array.isArray(raw.targetIds) ? raw.targetIds.map(String) : [],
    };
  } catch {
    return null;
  }
}

function writeRizomUvBridgeInstallRecord(rec: RizomUvBridgeInstallRecord): void {
  const dir = bridgesStateDir();
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const p = installRecordPath();
  const tmp = p + '.tmp';
  writeFileSync(tmp, JSON.stringify(rec, null, 2), 'utf8');
  renameSync(tmp, p);
}

function clearRizomUvBridgeInstallRecord(): void {
  const p = installRecordPath();
  if (!existsSync(p)) return;
  try {
    unlinkSync(p);
  } catch {
    /* ignore */
  }
}

function luaString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function buildRizomUvBridgeScript(port: number): string {
  const hb = heartbeatPath();
  return `-- AssetCutter RizomUV Bridge
-- Auto-generated by AssetCutter local companion.

local heartbeat_path = "${luaString(hb)}"
local port = ${port}

local function ensure_parent(path)
  local parent = string.match(path, "^(.*)[/\\\\][^/\\\\]+$")
  if parent then
    os.execute('mkdir "' .. parent .. '" 2>nul')
  end
end

ensure_parent(heartbeat_path)
local f = io.open(heartbeat_path, "w")
if f then
  f:write('{"ok":true,"host":"rizomuv","name":"RizomUV","port":' .. tostring(port) .. ',"at":"' .. os.date("!%Y-%m-%dT%H:%M:%SZ") .. '"}')
  f:close()
end
`;
}

async function probeRizomUvBridge(): Promise<{ ok: boolean; message: string; heartbeatPath: string }> {
  const p = heartbeatPath();
  if (!existsSync(p)) return { ok: false, message: 'RizomUV bridge heartbeat has not been seen yet. Run the AssetCutter Lua script inside RizomUV.', heartbeatPath: p };
  try {
    const stat = statSync(p);
    const ageMs = Date.now() - stat.mtimeMs;
    const json = JSON.parse(readFileSync(p, 'utf8')) as { host?: string };
    if (json.host !== 'rizomuv') return { ok: false, message: 'RizomUV bridge heartbeat is invalid.', heartbeatPath: p };
    const mins = Math.max(0, Math.round(ageMs / 60000));
    return { ok: true, message: `RizomUV bridge heartbeat detected ${mins} min ago.`, heartbeatPath: p };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { ok: false, message: `RizomUV bridge heartbeat cannot be read: ${msg}`, heartbeatPath: p };
  }
}

export async function getRizomUvBridgeStatus(opts?: { home?: string; scriptsDirs?: string[] }): Promise<RizomUvBridgeStatus> {
  const targets = discoverRizomUvBridgeTargets(opts);
  const install = readRizomUvBridgeInstallRecord();
  const port = install?.port || DEFAULT_RIZOMUV_BRIDGE_PORT;
  return {
    id: 'rizomuv',
    name: 'RizomUV',
    description: 'One-click Lua script bridge using a local heartbeat probe.',
    defaultPort: DEFAULT_RIZOMUV_BRIDGE_PORT,
    port,
    roots: discoverRizomUvRoots(opts?.home),
    targets,
    install,
    installed: targets.some((v) => v.hasScriptBridge) || Boolean(install?.scriptsDirs.length),
    probe: await probeRizomUvBridge(),
  };
}

function resolveInstallTargets(
  body: RizomUvBridgeInstallBody,
  discovered: RizomUvBridgeTarget[],
): { targets: RizomUvBridgeTarget[]; error?: string } {
  const byId = new Map(discovered.map((v) => [v.id, v]));
  const targets: RizomUvBridgeTarget[] = [];
  for (const id of body.targets || []) {
    const v = byId.get(String(id));
    if (v) targets.push(v);
  }
  for (const dirRaw of body.scriptsDirs || []) {
    const scriptsDir = resolve(String(dirRaw || '').trim());
    if (scriptsDir) targets.push(targetFromScriptsDir(scriptsDir));
  }
  const unique = Array.from(new Map(targets.map((v) => [v.scriptsDir, v])).values());
  if (!unique.length) return { targets: [], error: 'no_rizomuv_scripts_dir' };
  return { targets: unique };
}

export function installRizomUvBridge(
  body: RizomUvBridgeInstallBody = {},
):
  | { ok: true; port: number; installed: Array<{ targetId: string; scriptsDir: string; scriptPath: string }>; message: string }
  | { ok: false; error: string; message: string } {
  const port = normalizePort(body.port);
  const discovered = discoverRizomUvBridgeTargets({ home: body.home, scriptsDirs: body.scriptsDirs });
  const resolved = resolveInstallTargets(body, discovered);
  if (resolved.error || !resolved.targets.length) {
    return {
      ok: false,
      error: resolved.error || 'no_rizomuv_scripts_dir',
      message: 'No RizomUV Scripts folder was found. Choose the Scripts folder manually.',
    };
  }
  const installed: Array<{ targetId: string; scriptsDir: string; scriptPath: string }> = [];
  for (const target of resolved.targets) {
    mkdirSync(target.scriptsDir, { recursive: true });
    writeFileSync(target.scriptPath, buildRizomUvBridgeScript(port), 'utf8');
    installed.push({ targetId: target.id, scriptsDir: target.scriptsDir, scriptPath: target.scriptPath });
  }
  writeRizomUvBridgeInstallRecord({
    port,
    installedAt: new Date().toISOString(),
    scriptsDirs: installed.map((x) => x.scriptsDir),
    targetIds: installed.map((x) => x.targetId),
  });
  return { ok: true, port, installed, message: 'RizomUV bridge installed. Run the AssetCutter Lua script inside RizomUV, then probe connection.' };
}

export function uninstallRizomUvBridge(
  body: { targets?: string[]; scriptsDirs?: string[] } = {},
): { ok: true; removed: Array<{ scriptsDir: string; scriptPath: string }> } {
  const discovered = discoverRizomUvBridgeTargets({ scriptsDirs: body.scriptsDirs });
  const record = readRizomUvBridgeInstallRecord();
  const targets = new Map<string, RizomUvBridgeTarget>();
  for (const v of discovered) {
    if (!body.targets || body.targets.length === 0 || body.targets.includes(v.id)) targets.set(v.scriptsDir, v);
  }
  for (const dir of record?.scriptsDirs || []) targets.set(resolve(dir), targetFromScriptsDir(dir));
  const removed: Array<{ scriptsDir: string; scriptPath: string }> = [];
  for (const target of targets.values()) {
    if (!existsSync(target.scriptPath)) continue;
    try {
      unlinkSync(target.scriptPath);
      removed.push({ scriptsDir: target.scriptsDir, scriptPath: target.scriptPath });
    } catch {
      /* ignore */
    }
  }
  clearRizomUvBridgeInstallRecord();
  return { ok: true, removed };
}
