import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';
import { getRepositoryRoot } from '../repositoryVolume.js';

export const DEFAULT_SUBSTANCE_PAINTER_BRIDGE_PORT = 7031;
export const SUBSTANCE_PAINTER_BRIDGE_PLUGIN_NAME = 'assetcutter_substance_painter_bridge.py';

export type SubstancePainterBridgeTarget = {
  id: string;
  label: string;
  pluginDir: string;
  pluginPath: string;
  hasPluginBridge: boolean;
};

export type SubstancePainterBridgeInstallRecord = {
  port: number;
  installedAt: string;
  pluginDirs: string[];
  targetIds: string[];
};

export type SubstancePainterBridgeStatus = {
  id: 'substance-painter';
  name: string;
  description: string;
  defaultPort: number;
  port: number;
  roots: string[];
  targets: SubstancePainterBridgeTarget[];
  install: SubstancePainterBridgeInstallRecord | null;
  installed: boolean;
  probe: { ok: boolean; message: string };
};

export type SubstancePainterBridgeInstallBody = {
  targets?: string[];
  pluginDirs?: string[];
  port?: number;
  home?: string;
};

function bridgesStateDir(): string {
  const sb = process.env.COMPANION_SANDBOX_ROOT?.trim();
  if (sb) return resolve(join(sb, 'bridges'));
  return resolve(join(getRepositoryRoot(), '..', 'bridges'));
}

function installRecordPath(): string {
  return join(bridgesStateDir(), 'substance-painter-install.json');
}

function normalizePort(raw: unknown): number {
  const n = Number(raw);
  return Number.isFinite(n) && n > 0 && n <= 65535 ? Math.floor(n) : DEFAULT_SUBSTANCE_PAINTER_BRIDGE_PORT;
}

export function discoverSubstancePainterRoots(home = homedir()): string[] {
  const roots: string[] = [];
  const fromEnv = process.env.SUBSTANCE_PAINTER_USER_ROOT?.trim();
  if (fromEnv) roots.push(resolve(fromEnv));
  roots.push(resolve(join(home, 'Documents', 'Adobe', 'Adobe Substance 3D Painter')));
  roots.push(resolve(join(home, 'Documents', 'Allegorithmic', 'Substance Painter')));
  roots.push(resolve(join(home, 'Adobe', 'Adobe Substance 3D Painter')));
  const out: string[] = [];
  for (const root of roots) {
    try {
      if (existsSync(root) && statSync(root).isDirectory() && !out.includes(root)) out.push(root);
    } catch {
      /* ignore */
    }
  }
  return out;
}

function targetFromPluginDir(pluginDir: string): SubstancePainterBridgeTarget {
  const resolvedDir = resolve(pluginDir);
  return {
    id: `substance-painter::${resolvedDir}`,
    label: 'Substance Painter Python plugins',
    pluginDir: resolvedDir,
    pluginPath: join(resolvedDir, SUBSTANCE_PAINTER_BRIDGE_PLUGIN_NAME),
    hasPluginBridge: existsSync(join(resolvedDir, SUBSTANCE_PAINTER_BRIDGE_PLUGIN_NAME)),
  };
}

export function discoverSubstancePainterBridgeTargets(opts?: {
  home?: string;
  pluginDirs?: string[];
}): SubstancePainterBridgeTarget[] {
  const byDir = new Map<string, SubstancePainterBridgeTarget>();
  for (const root of discoverSubstancePainterRoots(opts?.home)) {
    byDir.set(resolve(join(root, 'python', 'plugins')), targetFromPluginDir(join(root, 'python', 'plugins')));
  }
  for (const dirRaw of opts?.pluginDirs || []) {
    const dir = resolve(String(dirRaw || '').trim());
    if (dir) byDir.set(dir, targetFromPluginDir(dir));
  }
  return Array.from(byDir.values()).sort((a, b) => a.pluginDir.localeCompare(b.pluginDir));
}

export function readSubstancePainterBridgeInstallRecord(): SubstancePainterBridgeInstallRecord | null {
  const p = installRecordPath();
  if (!existsSync(p)) return null;
  try {
    const raw = JSON.parse(readFileSync(p, 'utf8')) as SubstancePainterBridgeInstallRecord;
    return {
      port: normalizePort(raw.port),
      installedAt: typeof raw.installedAt === 'string' ? raw.installedAt : '',
      pluginDirs: Array.isArray(raw.pluginDirs) ? raw.pluginDirs.map(String) : [],
      targetIds: Array.isArray(raw.targetIds) ? raw.targetIds.map(String) : [],
    };
  } catch {
    return null;
  }
}

function writeSubstancePainterBridgeInstallRecord(rec: SubstancePainterBridgeInstallRecord): void {
  const dir = bridgesStateDir();
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const p = installRecordPath();
  const tmp = p + '.tmp';
  writeFileSync(tmp, JSON.stringify(rec, null, 2), 'utf8');
  renameSync(tmp, p);
}

function clearSubstancePainterBridgeInstallRecord(): void {
  const p = installRecordPath();
  if (!existsSync(p)) return;
  try {
    unlinkSync(p);
  } catch {
    /* ignore */
  }
}

function buildSubstancePainterPlugin(port: number): string {
  return `# AssetCutter Substance Painter Bridge
# Auto-generated by AssetCutter local companion.
import json
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer

PORT = ${port}
_server = None

class Handler(BaseHTTPRequestHandler):
    def log_message(self, *_args):
        return
    def _send(self, code, payload):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)
    def do_GET(self):
        if self.path.split("?", 1)[0] == "/health":
            self._send(200, {"ok": True, "host": "substance-painter"})
        else:
            self._send(404, {"ok": False, "error": "not_found"})

def start_plugin():
    global _server
    if _server:
        return
    try:
        _server = HTTPServer(("127.0.0.1", PORT), Handler)
        threading.Thread(target=_server.serve_forever, daemon=True).start()
        print("[AssetCutter Substance Painter Bridge] ready on 127.0.0.1:%s" % PORT)
    except OSError as e:
        print("[AssetCutter Substance Painter Bridge] failed: %s" % e)

def close_plugin():
    global _server
    if _server:
        _server.shutdown()
        _server.server_close()
        _server = None
`;
}

async function probeSubstancePainterBridge(port: number, timeoutMs = 1800): Promise<{ ok: boolean; message: string }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(`http://127.0.0.1:${port}/health`, { signal: controller.signal });
    if (!res.ok) return { ok: false, message: `Substance Painter bridge returned HTTP ${res.status}` };
    const json = (await res.json().catch(() => null)) as { ok?: boolean; host?: string } | null;
    return json && json.ok
      ? { ok: true, message: 'Substance Painter bridge connected' }
      : { ok: false, message: 'Substance Painter bridge response is invalid' };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { ok: false, message: `Substance Painter bridge is not reachable on 127.0.0.1:${port}: ${msg}` };
  } finally {
    clearTimeout(timer);
  }
}

export async function getSubstancePainterBridgeStatus(opts?: {
  home?: string;
  pluginDirs?: string[];
}): Promise<SubstancePainterBridgeStatus> {
  const targets = discoverSubstancePainterBridgeTargets(opts);
  const install = readSubstancePainterBridgeInstallRecord();
  const port = install?.port || DEFAULT_SUBSTANCE_PAINTER_BRIDGE_PORT;
  return {
    id: 'substance-painter',
    name: 'Substance Painter',
    description: 'One-click Python plugin bridge using a local HTTP probe.',
    defaultPort: DEFAULT_SUBSTANCE_PAINTER_BRIDGE_PORT,
    port,
    roots: discoverSubstancePainterRoots(opts?.home),
    targets,
    install,
    installed: targets.some((v) => v.hasPluginBridge) || Boolean(install?.pluginDirs.length),
    probe: await probeSubstancePainterBridge(port),
  };
}

function resolveInstallTargets(
  body: SubstancePainterBridgeInstallBody,
  discovered: SubstancePainterBridgeTarget[],
): { targets: SubstancePainterBridgeTarget[]; error?: string } {
  const byId = new Map(discovered.map((v) => [v.id, v]));
  const targets: SubstancePainterBridgeTarget[] = [];
  for (const id of body.targets || []) {
    const v = byId.get(String(id));
    if (v) targets.push(v);
  }
  for (const dirRaw of body.pluginDirs || []) {
    const pluginDir = resolve(String(dirRaw || '').trim());
    if (pluginDir) targets.push(targetFromPluginDir(pluginDir));
  }
  const unique = Array.from(new Map(targets.map((v) => [v.pluginDir, v])).values());
  if (!unique.length) return { targets: [], error: 'no_substance_painter_plugin_dir' };
  return { targets: unique };
}

export function installSubstancePainterBridge(
  body: SubstancePainterBridgeInstallBody = {},
):
  | { ok: true; port: number; installed: Array<{ targetId: string; pluginDir: string; pluginPath: string }>; message: string }
  | { ok: false; error: string; message: string } {
  const port = normalizePort(body.port);
  const discovered = discoverSubstancePainterBridgeTargets({ home: body.home, pluginDirs: body.pluginDirs });
  const resolved = resolveInstallTargets(body, discovered);
  if (resolved.error || !resolved.targets.length) {
    return {
      ok: false,
      error: resolved.error || 'no_substance_painter_plugin_dir',
      message: 'No Substance Painter python/plugins folder was found. Choose one manually.',
    };
  }
  const installed: Array<{ targetId: string; pluginDir: string; pluginPath: string }> = [];
  for (const target of resolved.targets) {
    mkdirSync(target.pluginDir, { recursive: true });
    writeFileSync(target.pluginPath, buildSubstancePainterPlugin(port), 'utf8');
    installed.push({ targetId: target.id, pluginDir: target.pluginDir, pluginPath: target.pluginPath });
  }
  writeSubstancePainterBridgeInstallRecord({
    port,
    installedAt: new Date().toISOString(),
    pluginDirs: installed.map((x) => x.pluginDir),
    targetIds: installed.map((x) => x.targetId),
  });
  return {
    ok: true,
    port,
    installed,
    message: 'Substance Painter bridge installed. Enable or restart the plugin in Substance Painter, then probe connection.',
  };
}

export function uninstallSubstancePainterBridge(
  body: { targets?: string[]; pluginDirs?: string[] } = {},
): { ok: true; removed: Array<{ pluginDir: string; pluginPath: string }> } {
  const discovered = discoverSubstancePainterBridgeTargets({ pluginDirs: body.pluginDirs });
  const record = readSubstancePainterBridgeInstallRecord();
  const targets = new Map<string, SubstancePainterBridgeTarget>();
  for (const v of discovered) {
    if (!body.targets || body.targets.length === 0 || body.targets.includes(v.id)) targets.set(v.pluginDir, v);
  }
  for (const dir of record?.pluginDirs || []) targets.set(resolve(dir), targetFromPluginDir(dir));
  const removed: Array<{ pluginDir: string; pluginPath: string }> = [];
  for (const target of targets.values()) {
    if (!existsSync(target.pluginPath)) continue;
    try {
      unlinkSync(target.pluginPath);
      removed.push({ pluginDir: target.pluginDir, pluginPath: target.pluginPath });
    } catch {
      /* ignore */
    }
  }
  clearSubstancePainterBridgeInstallRecord();
  return { ok: true, removed };
}
