import type { PriceCatalogEntry } from './usageBilling';

/** 官方公示价近似值（USD）；Phase 0 无 markup。运行时价目以 server/price-catalog-store.js 为准。 */
export const DEFAULT_PRICE_CATALOG: PriceCatalogEntry[] = [
  {
    billingSku: 'llm.gemini.flash',
    meterKind: 'token',
    inputPer1m: 0.15,
    outputPer1m: 0.6,
    displayName: 'Gemini 2.5 Flash (text)',
    vendorSkuRef: 'gemini-2.5-flash',
  },
  {
    billingSku: 'llm.gemini.pro',
    meterKind: 'token',
    inputPer1m: 1.25,
    outputPer1m: 10.0,
    displayName: 'Gemini 2.5 Pro (text)',
    vendorSkuRef: 'gemini-2.5-pro',
  },
  {
    billingSku: 'image.gemini.flash',
    meterKind: 'image',
    inputPer1m: 0.3,
    outputPer1m: 6.0,
    imageOutputPer1m: 60.0,
    perUnit: 0.039,
    displayName: 'Gemini Flash Image',
    vendorSkuRef: 'gemini-2.5-flash-image',
  },
  {
    billingSku: 'image.gemini.pro',
    meterKind: 'image',
    inputPer1m: 2.0,
    outputPer1m: 12.0,
    imageOutputPer1m: 120.0,
    perUnit: 0.134,
    displayName: 'Gemini Pro Image',
    vendorSkuRef: 'gemini-3-pro-image',
  },
  {
    billingSku: 'llm.openai.gpt4o-mini',
    meterKind: 'token',
    inputPer1m: 0.15,
    outputPer1m: 0.6,
    displayName: 'GPT-4o Mini',
    vendorSkuRef: 'gpt-4o-mini',
  },
  {
    billingSku: 'llm.openai.gpt4o',
    meterKind: 'token',
    inputPer1m: 2.5,
    outputPer1m: 10.0,
    displayName: 'GPT-4o',
    vendorSkuRef: 'gpt-4o',
  },
  {
    billingSku: 'copilot.codex.tokens',
    meterKind: 'token',
    inputPer1m: 0.15,
    outputPer1m: 0.6,
    userCreditsPerUnit: 1,
    displayName: 'Copilot Codex tokens',
    vendorSkuRef: 'codex-cli',
  },
  {
    billingSku: 'image.openai.gpt15',
    meterKind: 'image',
    inputPer1m: 5.0,
    outputPer1m: 10.0,
    imageOutputPer1m: 32.0,
    perUnit: 0.133,
    displayName: 'GPT Image 1.5',
    vendorSkuRef: 'gpt-image-1.5',
  },
  {
    billingSku: 'image.openai.gpt2',
    meterKind: 'image',
    inputPer1m: 5.0,
    outputPer1m: 10.0,
    imageOutputPer1m: 30.0,
    perUnit: 0.067,
    displayName: 'GPT Image 2',
    vendorSkuRef: 'gpt-image-2',
  },
  {
    billingSku: '3d.tripo.task',
    meterKind: 'task',
    perUnit: 0.5,
    displayName: 'Tripo 3D task (estimate)',
    vendorSkuRef: 'tripo-image-to-model',
  },
  {
    billingSku: '3d.tencent.pro',
    meterKind: 'task',
    perUnit: 0.8,
    displayName: '腾讯混元 3D 专业版 (estimate)',
    vendorSkuRef: 'hunyuan-to3d-pro',
  },
  {
    billingSku: '3d.tencent.rapid',
    meterKind: 'task',
    perUnit: 0.4,
    displayName: '腾讯混元 3D 极速版 (estimate)',
    vendorSkuRef: 'hunyuan-to3d-rapid',
  },
  {
    billingSku: 'video.workflow.task',
    meterKind: 'task',
    perUnit: 0.2,
    displayName: 'Workflow video task (estimate)',
  },
  {
    billingSku: 'image.jimeng.t2i-v40',
    meterKind: 'task',
    perUnit: 0.05,
    displayName: '即梦 图片 4.0 (estimate)',
    vendorSkuRef: 'jimeng_t2i_v40',
  },
  {
    billingSku: 'video.jimeng.ti2v-v30-pro',
    meterKind: 'task',
    perUnit: 0.25,
    displayName: '即梦 视频 3.0 Pro (estimate)',
    vendorSkuRef: 'jimeng_ti2v_v30_pro',
  },
  {
    billingSku: 'digital_human.jimeng.omnihuman-v10',
    meterKind: 'task',
    perUnit: 0.35,
    displayName: '即梦 OmniHuman 1.0 (estimate)',
    vendorSkuRef: 'omnihuman_v1',
  },
];
